### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by curtisblackwell** [AtomLinter/linter-phpcs#11]
I installed PHP CodeSniffer via Pear.

I tried restarting Atom. I tried setting the `'phpcsExecutablePath': '/usr/bin/phpcs'` and restarting Atom.

I can't seem to get any of the Linter-compatible PHP linters to work, but every other language I've tried is working.

Any other suggestions?

**Comment by hd-deman** [comment]
@curtisblackwell specify  '/usr/bin' as 'phpcsExecutablePath'

**Comment by curtisblackwell** [comment]
I just tried your suggestion, but it didn't fix my problem.

**Comment by hd-deman** [comment]
enable `debug` setting for Linter package and show me some output from console.

**Comment by curtisblackwell** [comment]
So apparently the CLI class isn't in there for some reason. I tried uninstalling and reinstalling PHP_CodeSniffer, but it didn't fix the problem.

Copying and pasting the console output doesn't retain the formatting, so here's a screenshot for helping to read it.

![screen shot 2015-01-13 at 1 29 54 am](https://cloud.githubusercontent.com/assets/468029/5706412/1e383d7c-9ac4-11e4-8219-b4654fce8436.png)


```
command and arguments ["/usr/bin/phpcs", "--report=checkstyle", "--warning-severity=1", "--standard=PSR2", "--ignore=*.blade.php,*.twig.php", "/var/folders/gm/kxdky8893yv4scw493hk9w0h0000gn/T/A…3656-1blosm6text.html.php/core.savage_content.php"]0: "/usr/bin/phpcs"1: "--report=checkstyle"2: "--warning-severity=1"3: "--standard=PSR2"4: "--ignore=*.blade.php,*.twig.php"5: "/var/folders/gm/kxdky8893yv4scw493hk9w0h0000gn/T/AtomLinter115013-3656-1blosm6text.html.php/core.savage_content.php"length: 6__proto__: Array[0]
utils.coffee:5 is node executable: false
utils.coffee:5 stdout 
Warning: include_once(PHP/CodeSniffer/CLI.php): failed to open stream: No such file or directory in /usr/bin/phpcs on line 21

Warning: include_once(): Failed opening 'PHP/CodeSniffer/CLI.php' for inclusion (include_path='.:') in /usr/bin/phpcs on line 21

Fatal error: Class 'PHP_CodeSniffer_CLI' not found in /usr/bin/phpcs on line 24

utils.coffee:5 phpcs returned LinterPhpcs {editor: TextEditor, cwd: "/Users/curtisblackwell/sites/builtwithstatamic/_add-ons/savage_content", subscriptions: CompositeDisposable, executionTimeout: 5000, executablePath: "/usr/bin"…}cmd: "phpcs --report=checkstyle --warning-severity=1 --standard=PSR2 --ignore=*.blade.php,*.twig.php"cwd: "/Users/curtisblackwell/sites/builtwithstatamic/_add-ons/savage_content"editor: TextEditorexecutablePath: "/usr/bin"executionTimeout: 5000subscriptions: CompositeDisposable__proto__: ctor []
```

**Comment by curtisblackwell** [comment]
Any thoughts?

**Comment by curtisblackwell** [comment]
Finally got this figured out thanks (mostly) to [this post](http://tedshd.logdown.com/posts/246406-php-install-phpcsphp-codesniffer).

Steps to solve on Mac OS X:

1. Open `/etc/php.ini`. If there isn't a `php.ini` in there, make one.
2. Verify your `include_path` has `/usr/share/pear` in it.  
Ex. `include_path = ".:/usr/share/pear"`
3. Rejoice.

**Comment by curtisblackwell** [comment]
An even easier installation method for Composer users would be to:

1. Install the [Composer version](https://packagist.org/packages/squizlabs/php_codesniffer).
2. Add `~/.composer/vendor/bin/` to your PATH.
3. Add this to `config.cson`:

    ```cson
    "linter-phpcs": {
      phpcsExecutablePath: "/Users/YOUR-USERNAME-HERE/.composer/vendor/bin/phpcs"
    }
    ```

**Comment by pmgouveia** [comment]
:(
