### ISSUE TITLE
Error: Unable to determine environment

### ISSUE THREAD

**Issue by ra100** [AtomLinter/linter-phpcs#115]
Not sure from which version/update (maybe 1st March) I'm getting this error.

and it's thrown from here
`.atom/packages/linter-phpcs/node_modules/atom-linter/node_modules/consistent-env/lib/helpers.js:75:11`

I already tried to update atom, uninstall/reinstall linter-phpcs, rebuild apm...
1.3.0 works fine.

**Comment by Arcanemagus** [comment]
This has so far been caused by issues with shell configuration scripts, @steelbrain care to help debug?

**Comment by steelbrain** [comment]
Can you please tell us the shell you're using?

**Comment by ra100** [comment]
@steelbrain now I see that problem is in my setup, probably. I'm using bash (in xubuntu), but .bashrc launches fish shell and that could cause trouble

**Comment by steelbrain** [comment]
@ra100 Oh yes, that would be the culprit :)

I would advise that instead of launching a fish shell from a bash shell, you change your shell to fish directly using `chsh`

**Comment by ra100** [comment]
Thanks, how stupid of me :)
