### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by EvanHerman** [AtomLinter/linter-phpcs#116]
Getting the following errors during install:

npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by Arcanemagus** [comment]
Are you getting that from `apm`? Have you tried installing from within Atom again?

**Comment by EvanHerman** [comment]
Yea, I'm receiving the error from the Atom package installer. It's strange because I just installed this on my home computer this past weekend without any issues. I also attempted to update node - but I think the issue is that the brace-expansion package isn't available anymore.

When lint-phpcs is installing, it hangs and throws the erorr abov - the line before the first line above is:
`
npm ERR! file C:\Users\user_name\.atom\.apm\brace-expansion\1.1.3\package\package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\user_name\.atom\.apm\brace-expansion\1.1.3\package\package.json
`

**Comment by Arcanemagus** [comment]
Hmmm, looks like that's a dependency of `minimatch`, however it installs just fine for me.
![image](https://cloud.githubusercontent.com/assets/427137/13609990/5c8c187c-e510-11e5-8c05-cfb9aecf7805.png)

I would try deleting the folder listed above, my guess is that `apm` failed to download the file properly and just keeps reusing the cached (bad) version.

**Comment by EvanHerman** [comment]
As a follow up, the `package.json` file that came bundled with `bracket-expansion` was a completely empty file (it simpy had `null,null,null,null,null`). I'm not sure why or how that happened.

Inside of the directory mentioned above: 
`C:\Users\user_name\.atom\.apm\brace-expansion\1.1.3\package\package.json`

There is a .zip called package.zip.

I extracted the package.json file contained in the .zip in that location - and re-tried the install and things seemed to have gone smoothly this time.

Not sure what happened, but glad I could find the solution and at least provide my workaround for anyone else who may encounter this issue.

I appreciate the quick responses, Arcanemagus!


Evan

**Comment by Arcanemagus** [comment]
`apm` seems to have issues with steps failing and then not notifying the user/stopping till things break due to it much later. I think a lot of it is due to the ancient version of `npm` that it acts as a wrapper around, but who knows for sure...

Anyway, glad you got it worked out!
