### ISSUE TITLE
Failed to spawn command phpcs. Make sure phpcs is installed and on your PATH

### ISSUE THREAD

**Issue by hartey11** [AtomLinter/linter-phpcs#118]
Hi,

Just installed this plugin but get the following error on startup.
"Failed to spawn command phpcs. Make sure phpcs is installed and on your PATH"

I installed PHP_CodeSniffer before without any issues.

```ShellSession
MacBook-Pro:htdocs Jonny$ pear install PHP_CodeSniffer
WARNING: channel "pear.php.net" has updated its protocols, use "pear channel-update pear.php.net" to update
downloading PHP_CodeSniffer-2.5.1.tgz ...
Starting to download PHP_CodeSniffer-2.5.1.tgz (484,780 bytes)
.................................................................................................done: 484,780 bytes
install ok: channel://pear.php.net/PHP_CodeSniffer-2.5.1
```

**Comment by pfefferle** [comment]
As the error message says, you either have to add the PHP_CodeSniffer bin to your directory or add the full path of your installation to the linter-phpcs settings.

**Comment by Arcanemagus** [comment]
If you open a terminal and type `which phpcs` is it able to be found there?

**Comment by hartey11** [comment]
yes "/Applications/MAMP/bin/php/php5.6.10/bin/phpcs"

Where are the linter-phpcs settings, can only see the README when I open Packages / Linter Phpcs?

**Comment by pfefferle** [comment]
I also have problems with "global" executables from time to time, mostly when I start Atom directly, not through the command line. In my case it helped to always use the complete path for executables.

**Comment by pfefferle** [comment]
Try to copy the whole path (`/Applications/MAMP/bin/php/php5.6.10/bin/phpcs`) to the "Executable Path" field.

**Comment by pfefferle** [comment]
You can find the settings by clicking on the "settings"-button or in the whole entry (not the headline).

**Comment by hartey11** [comment]
I haven't got an executable path field in the Linter Phpcs settings...just the README.

**Comment by pfefferle** [comment]
Can you post a screenshot?

**Comment by hartey11** [comment]
![screen shot 2016-03-11 at 09 45 50](https://cloud.githubusercontent.com/assets/6071669/13698776/24792046-e76e-11e5-8c6d-796f0a36e81a.png)

**Comment by hartey11** [comment]
Im guessing if i add it to my PATH sublime text etc will also be able to use it? if so, how do i add it to my PATH?

**Comment by pfefferle** [comment]
Oh, that is strange... I have no idea how to fix that, but you can try to add the setting through the `config.cson`. Hit "file" -> "Open your config" in the menu and add the following to the file:

```cson
"linter-phpcs":
    executablePath: "/Applications/MAMP/bin/php/php5.6.10/bin/phpcs"
```

**Comment by pfefferle** [comment]
PHPCS seems to be in your PATH otherwise `which phpcs` won't return anything...

**Comment by hartey11** [comment]
cool thanks adding that to the config worked!

**Comment by Arcanemagus** [comment]
From the path you posted it looks like you are on OS X, which provides applications launched from the GUI with an essentially empty environment. We have several workarounds in place for this, but they aren't perfect and sometimes miss things, which is why we have the `Executable Path` option allowing you to manually specify it :wink:

I'm glad @pfefferle was able to help you out here, and if you have any further issues feel free to file a new issue.

**Comment by DonRichards** [comment]
I just came across this error today. And I'm just places this link to fix it incase someone else is having the same issue. https://www.drupal.org/node/1419988
