### ISSUE TITLE
Have to edit file before linter will run

### ISSUE THREAD

**Issue by plessbd** [AtomLinter/linter-phpcs#120]
So if I open a file the linter will not run.  If I use the command pallet to run the linter it does not run.

I have to actually change the file before it runs.

Is this expected or could it be I have something wrong?

**Comment by Arcanemagus** [comment]
Running `Linter::Lint` from the command palette should work... and simply opening a file should also work, assuming you have Lint on Fly enabled in `Linter` itself.

**Comment by plessbd** [comment]
Lint as you Type: enabled with the default interval of 300ms

eslint works on file open and on Linter::Lint

**Comment by Arcanemagus** [comment]
What version of Atom, `linter`, and `linter-phpcs` are you on?

**Comment by plessbd** [comment]
I should have provided more details as well

Atom-Beta v1.6.0-beta8
linter 1.113
linter-eslint 7.11
linter-phpcs 1.3.1

**Comment by Arcanemagus** [comment]
Hmmm, I'm on those exact versions and am not seeing this, I'll check to see whether I just haven't noticed...

**Comment by plessbd** [comment]
also in case it matters: 
```
phpcs --version
PHP_CodeSniffer version 2.5.1 (stable) by Squiz (http://www.squiz.net)
```

I am running on a mac using homebrew to install phpcs

**Comment by plessbd** [comment]
so I decided to take the nuclear approach.

I completely reinstalled Atom, and all the plugins as well as php and phpcs

Everything works now.  So I am going to say that this was just a bad dependency or config somewhere that was not working.

Thank you for looking into it.

**Comment by Arcanemagus** [comment]
Glad to hear it's fixed, although who knows as to how... :confused:

Anyway, if you run into anything else just file an issue :wink:.

**Comment by Chimit** [comment]
Have the same behavior. `Linter::Lint` doesn't work for me too. Only changing a file starts Linter.

```
Atom 1.7.3
linter 1.11.4
linter-phpcs 1.3.2
PHP_CodeSniffer version 2.6.0 (stable) by Squiz (http://www.squiz.net)
```

**Comment by Arcanemagus** [comment]
@Chimit if you place a breakpoint [here](https://github.com/AtomLinter/linter-phpcs/blob/v1.3.2/lib/main.coffee#L101) is it getting triggered? What about one placed [here](https://github.com/AtomLinter/linter-phpcs/blob/v1.3.2/lib/main.coffee#L120)?

**Comment by MohammedAl-Mahdawi** [comment]
Same issue here, I run Ubuntu 16.04 with the latest versions of Atom and its packages, only changing the file starts Linter!
