### ISSUE TITLE
No setting for lint standard

### ISSUE THREAD

**Issue by henyihanwobushi** [AtomLinter/linter-phpcs#121]
May be a setting for phpcs ruleset is needed to customize the behavier of linter

**Comment by Arcanemagus** [comment]
Is there something the [current setting](https://github.com/AtomLinter/linter-phpcs/blob/v1.3.1/lib/main.coffee#L9) isn't accomplishing?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.

**Comment by robbieaverill** [comment]
@Arcanemagus can that setting be changed on a per-project level?

**Comment by Arcanemagus** [comment]
Not from this package, but then no package does that :stuck_out_tongue:.

If you want to change settings based on the project you are working on you might want to look into [project-manager](https://atom.io/packages/project-manager) as I understand it has this capability.

**Comment by robbieaverill** [comment]
Thanks

On Thu, Apr 14, 2016 at 9:25 AM, Landon Abney <notifications@github.com>
wrote:

> Not from this package, but then no package does that [image:
> :stuck_out_tongue:].
>
> If you want to change settings based on the project you are working on you
> might want to look into project-manager
> <https://atom.io/packages/project-manager> as I understand it has this
> capability.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AtomLinter/linter-phpcs/issues/121#issuecomment-209653019>
>



-- 
*Robbie Averill*
LA PETITE MANOUCHE - NZ Gypsy Jazz Guitar Duo
Phone: +64 27 321 4758
contact@lapetitemanouche.com
www.lapetitemanouche.com

**Comment by jyggen** [comment]
Another alternative is to just create a `phpcs.xml` file in your project root with the sole purpose of referencing the standard you want to use.

**Comment by robbieaverill** [comment]
Hi Jonas - if that is detected automatically by the parser, then great!

On Thu, Apr 14, 2016 at 9:27 AM, Jonas Stendahl <notifications@github.com>
wrote:

> Another alternative is to just create a phpcs.xml file in your project
> root with the sole purpose of referencing the standard you want to use.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AtomLinter/linter-phpcs/issues/121#issuecomment-209653544>
>



-- 
*Robbie Averill*
LA PETITE MANOUCHE - NZ Gypsy Jazz Guitar Duo
Phone: +64 27 321 4758
contact@lapetitemanouche.com
www.lapetitemanouche.com

**Comment by Arcanemagus** [comment]
As long as you haven't disabled the "Search for configuration files" setting then it should be :wink:.
