### ISSUE TITLE
Does not deliver messages to Nuclide's debugging pannel

### ISSUE THREAD

**Issue by AramZS** [AtomLinter/linter-phpcs#125]
All other linters I use will have their messages show in the Debugging Panel installed by Nuclide. However, phpcs, though working fine with the `linter` package, doesn't with Nuclide.

**Comment by Arcanemagus** [comment]
You'd have to file this on the Nuclide package, as you note this is working with the `linter` package and (as far as I know) follows the API specified there...

**Comment by Arcanemagus** [comment]
Have you put a breakpoint in the `lint()` function and made sure Nuclide is even triggering it?
