### ISSUE TITLE
Add an option to get PHPCS executable path from composer.json dynamically

### ISSUE THREAD

**Issue by nelson6e65** [AtomLinter/linter-phpcs#132]
This suggestion is about to use `vendor/bin/phpcs` as PHPCS ejecutable path (automatically) if project uses _PHP Code Sniffer_ (`"squizlabs/php_codesniffer"`) as requirement in `composer.json`: 

```js
"require-dev": {
	"squizlabs/php_codesniffer": "^2.6"
}
```

Something like `"Search for configuration files"` option.

**Comment by neolao** [comment]
It is not possible to include `phpcs` in the package ?

**Comment by Arcanemagus** [comment]
@neolao Not easily, at least not in a way that is cross platform.

**Comment by daltones** [comment]
:+1: Yeah! Totally agreed.

It carries the idea of everything _per project_. Also it's a common feature with node based linters like eslint, stylelint etc.
