### ISSUE TITLE
add fix for single rule

### ISSUE THREAD

**Issue by UziTech** [AtomLinter/linter-phpcs#141]
Not sure if there is a way but I would like to be able to fix a single rule by clicking on a button next to the description of a fixable rule

![image](https://cloud.githubusercontent.com/assets/97994/14724684/510ba4c8-07dd-11e6-9b6a-98c4a0ac0754.png)

**Comment by Arcanemagus** [comment]
If `phpcs` actually provides information on how to fix it in the message then we can just implement the [`fix` property](https://github.com/steelbrain/linter/wiki/Linter-API#fix) on what gets sent back to `linter`, if it however just has a mode to run it with then that can be implemented as a command users run, or gets triggered on save.

**Comment by UziTech** [comment]
There is a way to print a diff using `--report=diff`

https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically#printing-a-diff-report

This would probably need to be run on every fixable rule and parsed to set the fix property

**Comment by Arcanemagus** [comment]
I'm going to have to mark this as closed for now. It seems that PHPCS uses the `diff` _program_ internally to generate that output, as when you try to run that on Windows without that utility available it just fails with a message that `diff` isn't recognized.

From what I can tell of the output from the documentation, it never supported an individual fix in the first place, but rather printed a diff of all the recommended changes to the file. If you are still interested in the fix functionality though, please file a new issue requesting `phpcbf` integration as a command.
