### ISSUE TITLE
non-pear installation

### ISSUE THREAD

**Issue by ZeeCoder** [AtomLinter/linter-phpcs#143]
I installed phpcs using the curl method, and this is what i got:

<img width="466" alt="screen shot 2016-04-22 at 12 39 42" src="https://cloud.githubusercontent.com/assets/3679506/14739389/87fbfadc-0887-11e6-8f74-36c8f52ad746.png">

**Comment by jyggen** [comment]
Do you get the same error if you run the .phar file from the terminal?

**Comment by Arcanemagus** [comment]
That error is definitely being forwarded on from the `stderr` output of attempting to run `phpcs`.

**Comment by ZeeCoder** [comment]
It works fine when I run it from the console.

<img width="524" alt="screen shot 2016-04-23 at 22 26 38" src="https://cloud.githubusercontent.com/assets/3679506/14763822/84346b84-09a2-11e6-838d-7fb548a0993b.png">

**Comment by Arcanemagus** [comment]
I wonder if something in your configuration is broken in non-interactive shells?

If you close _all_ instances of Atom, then launch it from a terminal where your manual installation works from (`atom .`) does it work from within Atom?

**Comment by ZeeCoder** [comment]
It does the same thing :/

**Comment by Arcanemagus** [comment]
Something about your system's configuration is breaking the execution in non-interactive shells then. :confused:

**Comment by ZeeCoder** [comment]
Hmm, can ohmyzsh do something like this?

**Comment by Arcanemagus** [comment]
If you are loading it in non-interactive shells, definitely (you shouldn't need it there anyway). You should be guarding the loading of things like that so they are only done in interactive shells.

**Comment by jyggen** [comment]
Can you post the command you run from ohmyzsh as well as your phpcs.xml or similar (if you have one)?

**Comment by ZeeCoder** [comment]
I have no configuration.

asd.php:
```php
<?php

echo 'asd';

```

`phpcs asd.php`

Output:

```
FILE: /Users/zeecoder/work/js-presentation/asd.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 2 | ERROR | Missing file doc comment
----------------------------------------------------------------------

Time: 26ms; Memory: 3.75Mb
```


Atom setup:
<img width="865" alt="screen shot 2016-04-28 at 21 01 25" src="https://cloud.githubusercontent.com/assets/3679506/14899536/66a53e32-0d84-11e6-8e20-a931537fc14f.png">

**Comment by ZeeCoder** [comment]
I installed the composer version instead.

**Comment by daltones** [comment]
Same problem with .phar installation here.

Actually it’s a known phpcs bug: https://github.com/squizlabs/PHP_CodeSniffer/issues/944

Waiting for phpcs 2.6.1…

**Comment by Arcanemagus** [comment]
@daltones Thanks for tracking that down!
