### ISSUE TITLE
Wrong column when using tabs

### ISSUE THREAD

**Issue by UziTech** [AtomLinter/linter-phpcs#146]
The range for the errors is set as
```
startPoint = [message.line - 1, message.column - 1]
endPoint = [message.line - 1, message.column]
```

The second element is set as the column of the error but the range thinks it is the character of the line.

When using tabs the column of a line is not the same as the character.

![image](https://cloud.githubusercontent.com/assets/97994/14855117/10f15c46-0c58-11e6-99c6-fbf84ccbfa64.png)

The `t` is underlined because it is the 3rd character of the line but the `"` should have been underlined as it is in the 3rd column

**Comment by UziTech** [comment]
this will be fixed by a pull request to PHPCS 

https://github.com/squizlabs/PHP_CodeSniffer/pull/998

**Comment by UziTech** [comment]
I am reopening this issue as PHPCS refuses to fix it on their end

https://github.com/squizlabs/PHP_CodeSniffer/issues/982

**Comment by Arcanemagus** [comment]
Wow, just read through that issue. I can't say I'm surprised as the PHP linters are years behind modern linters like ESLint or Stylelint, and it doesn't look like they are interested in catching up any time soon.

Right now there is a [`tabWidth`](https://github.com/AtomLinter/linter-phpcs/blob/v1.4.0/lib/main.coffee#L43) option, which could be used to work around this limitation with some work. As Atom already has a way to define how many spaces a tab is equivalent to when displaying though I'm thinking about removing that option and just having it follow the Atom setting.

What do you think @UziTech?

**Comment by UziTech** [comment]
The `tabWidth` option is still needed since there are times when developers may not want to pass a [`--tab-width`](https://github.com/AtomLinter/linter-phpcs/blob/master/lib/main.coffee#L76) parameter to PHPCS

I think the solution will have to be recalculating the column by counting tabs as the number of characters in `tabWidth`

Atom already does this to an extent by converting between [`screenPosition` and `bufferPosition`](https://atom.io/docs/api/v1.10.0/TextEditor#buffer-vs-screen-coordinates). I submitted a [pull request](https://github.com/AtomLinter/linter-phpcs/pull/147) a while ago that converted between screen position and buffer position however this seems to introduce other issues when code is folded.

**Comment by Arcanemagus** [comment]
Ah, thought your name looked familiar 😛.

A couple of things from that: `rangeFromLineNumber` now only highlights the next "word" (as defined by the current language) instead of the rest of the line when given a column now, so ranges aren't quite as large. If it's not given a column it still highlights the entire line as it has no way of knowing what the linter meant in that case.

For this though it sounds like we need to manually calculate it 😞, as you said the folding messes up the rows for the screen position, so we can't use that.
