### ISSUE TITLE
Would it be possible to add a command to run phpcbf on current file?

### ISSUE THREAD

**Issue by jasuess** [AtomLinter/linter-phpcs#15]

**Comment by steelbrain** [comment]
Could you please explain?

**Comment by Arcanemagus** [comment]
I'm guessing they are talking about the phpcbf utility (also maintained by the phpcs group): https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically

However, this seems to be more in the scope of https://atom.io/packages/atom-beautify than in a linter.

**Comment by pfefferle** [comment]
If you only need a fixer for PHP, you can also try https://atom.io/packages/php-cs-fixer

**Comment by steelbrain** [comment]
Closing as invalid. and because AtomLinter base has implemented a new buffer modifying linter API that someone can use to build a package like that.
