### ISSUE TITLE
Cant add 0 (zero) in setting for warning severity

### ISSUE THREAD

**Issue by jghaanstra** [AtomLinter/linter-phpcs#154]
I'm trying to set the warning severity to only display errors. Configuration indicates that I should enter a 0 (zero) in the setting for warning severity. I'm however unable to do so as the field seems to expect a positive integer and thus not allowing a 0.

Using Atom 1.7.3 on Windows 10 and linter-phpcs 1.4.0.

**Comment by Arcanemagus** [comment]
There is no checking of the value being done... it's merely sent straight on to `phpcs`. Where are you seeing that it is "not allowing a 0"?

**Comment by jghaanstra** [comment]
It wont allow me to save the value 0 in the config field, it defaults back to the default value 1. But if this value is sent 1-on-1 to phpcs I guess the value for display errors only would  be the letter n as this is the phpcs parameter for only showing errors.

Although I can add the letter n this does not set the warning severity to errors only.

**Comment by Arcanemagus** [comment]
Hmmm, it seems at some point `integer` was changed to only positive integers :confused:, looking into this...

**Comment by Arcanemagus** [comment]
Filed an issue on the Atom repo, it looks like there is a bug with attempting to set the value `0` period. :confused:

**Comment by jghaanstra** [comment]
Ok, thanx for looking into this. I'll keep track there.

**Comment by henriquebremenkanp** [comment]
I just submited a PR with a possible solution, adding a checkbox. I hope you like it.

![screen shot 2016-05-11 at 12 37 53 am](https://cloud.githubusercontent.com/assets/3855603/15169447/bbf2f226-1711-11e6-81ce-211198409263.png)

![cuqenzdatv](https://cloud.githubusercontent.com/assets/3855603/15169449/c0764d16-1711-11e6-8ff2-6a688f6806c7.gif)

**Comment by jghaanstra** [comment]
It would solve my issue for now indeed as long as the Atom issue itself is not fixed. Thanx.

**Comment by Arcanemagus** [comment]
It looks like this fix hadn't been published yet! It's out now in v1.4.1. 🎉

**Comment by Arcanemagus** [comment]
The underlying issue in `atom/settings-view` was fixed in a version first included in Atom v1.8.0 as well, so you should be able to directly set it to 0 now, regardless of the other setting. Marking this as closed due to that.
