### ISSUE TITLE
Update `atom-linter` to ^5.0.2

### ISSUE THREAD

**Issue by phoenixenero** [AtomLinter/linter-phpcs#158]
[`atom-linter` changelog](https://github.com/steelbrain/atom-linter/blob/master/CHANGELOG.md)

Should fix this particularly annoying error:

![ss 2016-05-10 at 09 54 17](https://cloud.githubusercontent.com/assets/9031092/15133412/2f09a8cc-1695-11e6-8f2e-f2bc6b8cddc6.png)

**Comment by Arcanemagus** [comment]
There is no such version as v5.0.2 (yet), I think you mean v5.0.1...

Work on updating to that is taking place [here](https://github.com/AtomLinter/linter-phpcs/pull/156), but it seems that version is broken in a different way on Windows.

If you have Node.js installed you can fix this by running the following in the `linter-phpcs` folder:
```shell
npm install atom-linter@~4.6.0
```
