### ISSUE TITLE
how to set 1 line for display the error ?

### ISSUE THREAD

**Issue by oknixus** [AtomLinter/linter-phpcs#161]
Now it's 2 line.
![screenshot from 2016-05-26 21 27 17](https://cloud.githubusercontent.com/assets/4592706/15576184/3c03e65e-2389-11e6-8ad3-2d752dc20fe6.png)

I can not find the setting in linter-phpcs.

Please help me, thanks very much.

**Comment by Arcanemagus** [comment]
You should be able to drag the top of that panel down till it is only 1 line, if not you should file an issue on [linter](https://github.com/steelbrain/linter) as this project has nothing to do with the UI.

**Comment by oknixus** [comment]
Sorry，I have a try. But the mouse always display a Capital I
I just press the left key of the mouse, then move, the mouse became to a 2 arrows and a  vertical line.
It hides so deep.

Thanks and sorry for my ignorance.
Thanks.
