### ISSUE TITLE
exclude sniffs option

### ISSUE THREAD

**Issue by Pross** [AtomLinter/linter-phpcs#168]
Recent commit of phpcs allows you to exclude sniffs via the commandline.

It isn't in the released version yet, but can this be added as an option when it is.

https://github.com/squizlabs/PHP_CodeSniffer/commit/c287c99060fbe7f94bd685b4d847113714f239c5

**Comment by Arcanemagus** [comment]
Just a note that this is [now released](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/2.6.2).
