### ISSUE TITLE
Something went wrong attempting to parse the PHPCS output.

### ISSUE THREAD

**Issue by rshmiraf** [AtomLinter/linter-phpcs#178]
It doesn't work for me. Pear and PHP work well on my terminal.

[
![zrzut ekranu 2016-07-30 o 15 50 01](https://cloud.githubusercontent.com/assets/14861637/17270866/516ca0fa-566d-11e6-9c7d-dec0a8fb487e.png)
](url)

![zrzut ekranu 2016-07-30 o 15 53 38](https://cloud.githubusercontent.com/assets/14861637/17270915/26e28632-566e-11e6-8d4a-d93bac680c84.png)

**Comment by jyggen** [comment]
If you open the dev tools in Atom do you see any "better" error messages?

**Comment by rshmiraf** [comment]
> If you open the dev tools in Atom do you see any "better" error messages?

look at this. By changing source (commented) it work - where i made mistake?
![zrzut ekranu 2016-07-30 o 19 48 00](https://cloud.githubusercontent.com/assets/14861637/17272121/baa33ca2-568e-11e6-8d1c-c85e7f0fd84b.png)

**Comment by Arcanemagus** [comment]
Are you trying to develop your own modified version of `phpcs`.... while using it to check itself? 😕

You seem to have this package using `/usr/local/bin/phpcs` as the path to `phpcs`, but you are editing that file in Atom...

**Comment by Arcanemagus** [comment]
Marking this as closed due to a lack of response.
