### ISSUE TITLE
Would it be possible to add support to php-cs-fixer instead of code sniffer?

### ISSUE THREAD

**Issue by akoury** [AtomLinter/linter-phpcs#181]
[PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)

**Comment by Arcanemagus** [comment]
I'm not entirely sure what you are asking here... this package is an integration layer between `phpcs` and the Atom `linter` package, allowing the messages from `phpcs` to be shown in Atom.

`php-cs-fixer` seems to be a tool that automatically fixes some code style issues. Maybe you want to write an Atom package that allows running it on the currently open file?

**Comment by akoury** [comment]
I originally thought that phpcs and php-cs-fixer did the same things, correct errors on php coding standards, that is why i was asking if it was possible to use php-cs-fixer instead, however, reading through the phpcs package i see that it actually has 2 scripts, one that detects the violations and another that makes the corrections.

I assume that the one that the linter uses is the script that detects violations therefore it is able to show the errors, since php-cs-fixer does not have that script i dont think it would be a viable replacement.

Sorry for my confusion!
