### ISSUE TITLE
PHP Notice: Undefined offset with double quotes

### ISSUE THREAD

**Issue by thomashigginbotham** [AtomLinter/linter-phpcs#186]
I receive an error any time I add an opening `<?php` inside of an HTML attribute. If I don't quickly add the `?>`, then the error will appear. It has something to do with the double-quotation mark that is auto-inserted by Atom after typing the first double-quote.

Example of HTML that causes the issue:

```
<input value="<?php "
```

Error: PHP Notice: Undefined offset: 677 in /usr/local/pear/share/pear/PHP/CodeSniffer/Standards/Squiz/Sniffs/Strings/DoubleQuoteUsageSniff.php on line 72

**Comment by jyggen** [comment]
CodeSniffer isn't good at linting the file before parsing it, so those errors are expected when CodeSniffer is executed on invalid PHP files sadly. Not sure if there's anything this plugin can do about it.

**Comment by UziTech** [comment]
This is an issue with the sniff [DoubleQuoteUsageSniff](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Sniffs/Strings/DoubleQuoteUsageSniff.php).

Usually sniffs should fail silently to avoid this type of error. You can submit an issue on [squizlabs/PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer/issues/new)

**Comment by Arcanemagus** [comment]
Closing as an external issue based on the above. if you do file that over there please link back here so anyone finding this can see the resolution!
