### ISSUE TITLE
Error: Column start greater than line length

### ISSUE THREAD

**Issue by robneu** [AtomLinter/linter-phpcs#204]
I'm getting the following error on quite a few files after updating to `1.5.0`

```
Error: Column start (25) greater than line length (20)
    at Object.rangeFromLineNumber (/Users/robertneu/.atom/packages/linter-phpcs/node_modules/atom-linter/lib/index.js:179:11)
    at /Users/robertneu/.atom/packages/linter-phpcs/lib/main.js:324:28
    at Array.map (native)
    at Object.<anonymous> (/Users/robertneu/.atom/packages/linter-phpcs/lib/main.js:312:25)
    at undefined.next (native)
    at step (/Users/robertneu/.atom/packages/linter-phpcs/lib/main.js:9:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by dutchauser** [comment]
I am also getting the same error after updating. The machine running the 1.4.1 version is unaffected.

**Comment by Arcanemagus** [comment]
One of the things we've seen is that the newer version of the helper library has much better detection of invalid points from the linter.

Are you able to share the file being linted and the relevant configuration?

**Comment by robneu** [comment]
This file has quite a lot of lint errors and was one of the ones throwing that error when being linted: https://github.com/robneu/social-warfare/blob/master/functions/admin-options-page/admin-options-array.php

What configuration are you looking for? phpcs? Atom? Atom Linter?

**Comment by Arcanemagus** [comment]
The PHPCS configuration, if you aren't using the default of `PSR2`. I'll check this out in a bit and see if I can replicate this locally.

**Comment by robneu** [comment]
Ah, sorry. I'm using the [WordPress](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards) coding standards on that project.

**Comment by Arcanemagus** [comment]
Okay, turns out even this is enough to reproduce at least one of the bugs:
```php
<?php
	function foo($bar) {
	}
?>
```

Apparently PHPCS completely barfs if the entire function is indented for no reason, which you have on line 8 of your file. The offending sniff is `Squiz.Functions.MultiLineFunctionDeclaration.BraceOnSameLine`.

Looking through this to see if any more bugs in PHPCS surface in this file 😛.

**Comment by Arcanemagus** [comment]
Ah, I'll run through with that coding standard as well.

**Comment by Arcanemagus** [comment]
Okay, on further investigation this is a combination of PHPCS bugs, and a "bug" in our attempt to fix it on our end as currently the author has refused to fix it.

PHPCS, unlike _every_ other linter, doesn't consider tabs to be a single character. We have a setting that allows you to set how many spaces it converts them to, but by default it does nothing. It seems that although PHPCS [claims](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-default-tab-width) to not mess with them by default, most sniffs have decided on their own that a tab is equivalent to 4 spaces by default.

The "bug" here was that if you haven't specified an override, it was using 1 for the tab length, meaning each tab would push the column given by PHPCS 3 spaces farther than it should be. I'm putting up a PR that defaults the number of characters we replace it with to 4, but only if you haven't set an override in the settings as the override is passed on to PHPCS so it should theoretically be handled properly in that case.

For more details see https://github.com/squizlabs/PHP_CodeSniffer/issues/982.

**Comment by Arcanemagus** [comment]
v1.5.1 should "fix" this for you, please test it out as I don't use tabs in my own code.

**Comment by robneu** [comment]
Yup, seems good on my end. Thanks for patching it so quickly! 💯

**Comment by dutchauser** [comment]
I can also confirm that the patch has done the trick, many thanks for your efforts.

**Comment by miniwark** [comment]
I still have this bug when editing a file with v1.5.1. Here the error message in Atom:

```
Error: Column start (129) greater than line length (127)
    at Object.rangeFromLineNumber (/home/myuser/.atom/packages/linter-phpcs/node_modules/atom-linter/lib/index.js:179:11)
    at /home/myuser/.atom/packages/linter-phpcs/lib/main.js:319:28
    at Array.map (native)
    at Object.<anonymous> (/home/myuser/.atom/packages/linter-phpcs/lib/main.js:305:25)
    at undefined.next (native)
    at step (/home/myuser/.atom/packages/linter-phpcs/lib/main.js:9:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

I do not use tabs in the affected file.

**Comment by Arcanemagus** [comment]
@miniwark Can you try re-installing the package? You shouldn't be getting an error message like that in v1.5.1, it should be showing a notification of `Invalid point encountered! See console for details.` with the original message shown in the Developer Tools console.
