### ISSUE TITLE
Linter warnings not appearing in editor

### ISSUE THREAD

**Issue by randerson12** [AtomLinter/linter-phpcs#21]
After updating to Atom version 0.199.0 and phpcs version 2.3.2, I no longer see any phpcs linter warnings in the editor; however, PHP and PHPMD linter warnings are still being displayed. All of the package settings are set to default except for the phpcs executable path, which I've confirmed is set to the correct value. I've also confirmed that my phpcs tool still works properly from the command line.

This issue may have been caused by the latest update to phpcs since my [SublimeLinter-phpcs](https://github.com/SublimeLinter/SublimeLinter-phpcs) plugin seems to be similarly broken as well in ST3. I installed phpcs in Homebrew via the php-code-sniffer formula in [Homebrew/homebrew-php](https://github.com/Homebrew/homebrew-php) and I'm running OS X 10.10.3.

**Comment by jaswsinc** [comment]
Same homebrew installation, same exact issue.

**Comment by randerson12** [comment]
This seems to be an issue with the Homebrew installation of the PHPCS utility itself rather than with the package. Attempting to run it from the command line with the PSR2 standard caused an error. Manually modifying the Homebrew formula to download the prior version (2.3.0) fixed the issue. To do so, I did the following:

- Open /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php-code-sniffer.rb
- Delete all contents of the file
- Paste the contents of https://raw.githubusercontent.com/Homebrew/homebrew-php/c6e288e478c5813ffb6cc057d95543555ec5e919/Formula/php-code-sniffer.rb into the file
- Reinstall php-code-sniffer through Homebrew
- Pin the modified formula using `brew pin php-code-sniffer` so that it isn't upgraded
