### ISSUE TITLE
[1.5.3] Checking ignored blade files 

### ISSUE THREAD

**Issue by josebailo** [AtomLinter/linter-phpcs#213]
Hi, I updated to 1.5.3 version this morning and I'm having a trouble. Even though I have the default ignore patterns in settings (`*.blade.php, *.twig.php`), when I edit a `.blade.php` file the linter is checking it and showing the next warning:

```
PHPCS WARNING Internal.NoCodeFound No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.at line 1 col 1
```

I suppose it's a bug...

**Comment by Arcanemagus** [comment]
Hmmm, if you open Atom's Developer Tools and run `atom.config.get('linter-phpcs.ignorePatterns')` what do you get?

**Comment by josebailo** [comment]
I get `["*.blade.php", "*.twig.php"]`.

The full path is `resources/views/*`, the default view's path for laravel framework.

**Comment by Arcanemagus** [comment]
Whoops, forgot the key bit of information: What version of `phpcs` are you using?

Also, I meant the _full_ path, as in `/home/josebailo/code/projectname/resources/views/someName.blade.php`. You can anonymise parts, but don't remove them as I need to check this against whichever method is being used to ignore the file.

**Comment by josebailo** [comment]
The `phpcs`version is 2.6.1.

The routes are:
- `/var/www/project/resources/views/file.blade.php`
- `/var/www/project/resources/views/folder/file.blade.php`
- `/var/www/project/resources/views/folder/subfolder/file.blade.php`

Wherever the file is, fails.

Just now I've noticed that the warning is shown when I save the file and the cursor is above php code. For example, I have the next code in a `.blade.php` file, no matter where it is:

    @if (isset($errors) && count($errors) > 0)
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>

            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

If I save the file with the cursor above the parenthesis  or curly braces content the warning is shown, but if the cursor is somewhere else it doesn't. Even above the `@if`, `@foreach`... blade tags it isn't shown, just above strictly php code.

**Comment by josebailo** [comment]
Just updated `phpcs` to 2.7.0 but the problem remains.

**Comment by aceat64** [comment]
I'm having this same issue with `phpcs` version 2.3.3.

**Comment by josebailo** [comment]
Any news about this?

**Comment by jyggen** [comment]
Yeah, I believe this is an issue with the fallback when running PHP_CodeSniffer versions lower than 3.0.

```javascript
} else if (ignorePatterns.some(pattern => minimatch(filePath, pattern))) {
    // We must determine this ourself for lower versions
    return [];
}
```

Unable to test this properly myself right now, but using an [online tester for minimatch](http://www.globtester.com/) it definitely don't think `*.blade.php` matches `/var/www/project/resources/views/file.blade.php`. If I match it against the basename (`file.blade.php`) it matches though, so I believe something needs to be fixed :)

**Comment by johanderuijter** [comment]
I came across something similar myself, though not with blade templates.

In my case, adding `/**/` in front worked, so that would be `/**/*.blade.php` for blade files.

**Comment by aceat64** [comment]
@johanderuijter that work-around works for me as well

**Comment by josebailo** [comment]
Yes, @johanderuijter's solution works!

Thank you :smile:

**Comment by Arcanemagus** [comment]
I believe that changing the defaults to that should still work for PHPCS v3 and up as well.

**Comment by pedzed** [comment]
I am not sure what I did, but now it works fine. I think that I upgraded the CodeSniffer. That did not work initially, but I think that's because I had to reopen the file.
