### ISSUE TITLE
PEAR not necessary

### ISSUE THREAD

**Issue by curtisblackwell** [AtomLinter/linter-phpcs#215]
I just successfully used `brew install php-code-sniffer`. Homebrew is *probably* a bit more common than PEAR now, so it might be worth adding to the README.

Happy to submit a PR if you'll accept.

**Comment by Arcanemagus** [comment]
`pear` is cross-platform, `brew` is most definitely _not_ lol.

That being said, the documentation does need some updating as the PHP_CodeSniffer project lives [here](https://github.com/squizlabs/PHP_CodeSniffer) now, and `composer` seems to do a much better job of installing things in a usable manner.

**Comment by curtisblackwell** [comment]
Ah, that's a good point. I often forget some devs don't use Macs. 

I'd still recommend rewording and linking to match the other step(s) (PEAR could be removed). On my previous machine, I installed PEAR for no other reason, thinking it was necessary. This time I was smarter and looked it up.

**Comment by pedzed** [comment]
I just wanted to say the same. Please link to https://github.com/squizlabs/PHP_CodeSniffer rather than PEAR, because PEAR is so confusing and "old". I just could not find the GitHub link from there which I knew existed.
