### ISSUE TITLE
Error: Process exited with non-zero code: 255

### ISSUE THREAD

**Issue by mikebronner** [AtomLinter/linter-phpcs#224]
I'm regularly (as in every time I try to edit a PHP file) getting the following error message:

```
Error: Process exited with non-zero code: 255
    at ChildProcess.<anonymous> (/Users/mike/.atom/packages/linter-phpcs/node_modules/sb-exec/lib/index.js:60:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Atom: 1.12.7
Linter: 1.11.18
linter-phpcs: 1.5.4
PHPCS: 2.7.1

<img width="849" alt="screen shot 2016-12-14 at 9 11 25 am" src="https://cloud.githubusercontent.com/assets/1791050/21192420/5c23e734-c1dd-11e6-91ce-41c2da759061.png">

**Comment by Arcanemagus** [comment]
Are you using any other linters? This package ignores the exit code returned by `phpcs`, however the library is used by many linter plugins so it's likely this isn't actually the package that is causing your issue.

**Comment by mikebronner** [comment]
@Arcanemagus thanks for the response. I am also using PHPMD, but I don't have any other linters that are actively using PHPCS (I disabled that in other linters). I will try again.

**Comment by Arcanemagus** [comment]
If you installed PHPCS using PEAR it's also possible you are running into #206.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response and likely duplicate issue.
