### ISSUE TITLE
Error when saving (executing php-cs-fixer)

### ISSUE THREAD

**Issue by mikeerickson** [AtomLinter/linter-phpcs#226]
I am receiving the following error when saving files.  I know all works as I can run from CLI and no issues.  I have php-cs-fixer installed globally AND local to project (is this an issue)

![image](https://cloud.githubusercontent.com/assets/183153/21533785/2181beb2-cd13-11e6-9c2b-dfedd1dd99f6.png)

**Comment by Arcanemagus** [comment]
First of all that error is coming from the `stderr` stream of whatever you have set in the Executable Path setting and has nothing to do with this package.

Secondly, from the error it looks like you are trying to run some `php-cs-fixer` program, which isn't what this is designed to work with. Please follow [the instruction](https://github.com/AtomLinter/linter-phpcs#phpcs-installation) to install PHPCS. Once install the default setting for Executable Path should work just fine, if not you can set it manually to the result of `which phpcs`.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
