### ISSUE TITLE
Freezing pc 

### ISSUE THREAD

**Issue by onedal88** [AtomLinter/linter-phpcs#237]
Hi, 
with [custom ruleset](https://gist.github.com/onedal88/742e4ea037bff7b59500bcd96c755134) linter eat up all memory and CPU, i must restart computer every time. Execute timeout enabling/disabling have no effect.

OS: Debian Jessie
Linter-phpcs version: 1.5.8
PHP-CodeSniffer version: 2.7.0

With default PSR2 all working fine.

**Comment by weirdan** [comment]
Do you have an example php file that causes this? I tried simple php script (see below) with your ruleset, and had no problems (js heap jumped up just a couple MBs). Also, do you know if its atom eating memory, or phpcs itself? Try running phpcs directly from the command line.
```php
<?php
namespace Q;

use B;
use A;

class q
{

}
```
