### ISSUE TITLE
PHP process stuck at 100% CPU on macOS

### ISSUE THREAD

**Issue by mckernanin** [AtomLinter/linter-phpcs#239]
I've had this issue intermittently for a while, and on 2 different macbooks. After a while of having Atom open, the PHP process pegs at 100%. I can run `killall php` in a terminal and quickly fix it, but sometimes I only notice because my battery dies really quickly. Running phpcs from the terminal doesn't hang like this, and I use Atom all the time with it working properly, without PHP freezing on me.

I'm using the [WordPress Coding Sandards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards), but I have used PSR2 with Laravel and have seen similar issues.

A stopgap I found is a script like this, which watches for processes eating your CPU for X amount of time (default 5 minutes): https://blog.omgmog.net/post/getting-notified-when-a-process-is-using-100-cpu-on-mac-os-x/

**Comment by Arcanemagus** [comment]
This bug is _precisely_ why the execution timeout was even implemented in the first place. It _should_ be killing any process spawned after 10 seconds of running. Have you enabled the "Disable Execution Timeout" setting that turns off this check?

Btw, this package simply executes `phpcs` in a shell and then interprets the results it gets back, there isn't really any difference from running it in the CLI other than potentially the environment variables. It just seems that on some systems running it many times (on every file edit) it will randomly lock up.

**Comment by mckernanin** [comment]
I do not have execution timeout turned off, it doesn't seem to be respecting that setting

**Comment by mundschenk-at** [comment]
I can confirm the issue as well. The execution timeout is not disabled, yet the PHP processes run away merrily. Maybe a Sierra problem?

**Comment by mathieuhays** [comment]
I confirm that's happening for me as well. A lot of php processes remain open in my Activity Monitor.
Thanks to the info screen I could also notice that some processes are still running even though I closed the corresponding project directory. (closed the window). I've got 11 php processes running at 33% CPU.

**Comment by joehoyle** [comment]
This bug is responsible for burning my battery down on several occasions, it's not until I notice I'm on 20% after an hour of usage my heart sinks as I realise what has happened!

Maybe the process kill needs to kill children too or something?

**Comment by joehoyle** [comment]
Looking at https://github.com/AtomLinter/linter-phpcs/blob/2573af6f6c0a3b0f508e5bcca49b941833c20038/lib/main.js#L280 no timeout is explicitly set, are you presuming the default is 10 seconds, or is this set somewhere else?

**Comment by mckernanin** [comment]
Here's a PR with an option to explicitly set the timeout. I think @joehoyle might be on to something, so I'm giving this a shot locally.

**Comment by Arcanemagus** [comment]
@joehoyle Thanks for asking that, I went to the source of `sb-exec` to point out where it was being set... only to find that it _wasn't_. It turns out when the `exec()` function was moved out of `atom-linter` into its own module that got lost and never got added back!

**Comment by Arcanemagus** [comment]
(Note that all of this is only a band-aid on the fact that `phpcs` decides to sometimes become completely stuck and never exit.)

**Comment by mckernanin** [comment]
Thanks Landon! I was just testing out a bandaid.

**Comment by Arcanemagus** [comment]
This has been an issue with `phpcs` for a long enough time that it is actually the reason that timeout was introduced in `exec()` in the first place. 😞

**Comment by sybrew** [comment]
I'm still experiencing this issue. Am I missing something?

**Comment by mundschenk-at** [comment]
Since Atom updated itself to 1.18.0, this bug seems to crop up again (i.e. the `php` process continues to run forever with a high load).
