### ISSUE TITLE
Functionality of the logger showing warning/errors, etc...

### ISSUE THREAD

**Issue by futuretechmag** [AtomLinter/linter-phpcs#244]
Hey guys, really simple question (I'd ask on IRC but didn't want to burst into #atom) is the expected functionality to append any new warnings/errors to the bottom of existing ones?

Example would be Warning/Error on line 21, first and only one. I then add a define(...) on line 2 and it seems to append the Warning for FoundWithSymbols instead of prepending it, which IMO would deserve to be prepended since line 2 is before line 21?

However, if I'm first loading the file, of course it puts the log in order by line number, but "real-time" it doesn't seem to?

**Comment by Arcanemagus** [comment]
I _think_ this was an oddity in how Linter v1 handled messages, Linter v2 is out now though and sorts messages by position for you.
