### ISSUE TITLE
Multiple php processes

### ISSUE THREAD

**Issue by miklb** [AtomLinter/linter-phpcs#247]
Recently encountering issue with an error being thrown to check console for more info in Atom, and multiple php processes being spawned running > 90% CPU.

`PHP_CodeSniffer version 2.8.1 (stable)`
Atom version 1.15, macOS 10.12.4

Please let me know if I can provide any additional info, I'm not sure what console the error is referring to.

**Comment by kopepasah** [comment]
I too noticed this issue.

You can kill the processes by running `killall php`, but that should not be a permanent solution.

**Comment by sybrew** [comment]
Example code that will spawn permanent processes:
```
<?php
// This will definitely work:
array(
	$arg['test'] => $
	$arg['test']
);

// This also works:
array(
	'key' =>     // I just started writing!
)
```

I've drowned 10 polar bears so far 😄.

**Comment by Arcanemagus** [comment]
Just as an FYI, this is a PHPCS bug that can't really be fixed here. In #255 though I've implemented unique spawning per file being linted, so at most you should only have a process running for each open file.

@sybrew That's the first bit of code I've seen that supposedly reproduces this, have you filed it on the PHPCS repo?
