### ISSUE TITLE
no css classes inlcuded in linter table output

### ISSUE THREAD

**Issue by frontalnugity** [AtomLinter/linter-phpcs#251]
It looks like with a recent update the table and rows created for linter-output no longer includes and class-names assigned to the table and tooltip output.

I'm not sure if this is a phpcs issue or more to the linter package itself - but it does make it very difficult to style linter output without any classes to update.

Any suggestions or workarounds?

**Comment by Fernando-Marquardt** [comment]
The linter changed the way it output the messages. There is no HTML output anymore, only plain text and Markdown.

So, if you want to customize the output style, I think it is a linter issue, more specifically with [linter-ui-default](https://github.com/steelbrain/linter-ui-default).

**Comment by frontalnugity** [comment]
Thanks so kindly - that narrowed it down perfectly so I can either make a local adjustment and then maybe even a PR back. :)

Much appreciated!
