### ISSUE TITLE
Error running PHPCS Error: Invalid point encountered! See console for details

### ISSUE THREAD

**Issue by ashickurnoor** [AtomLinter/linter-phpcs#252]
Hi

I am very new to Atom. I was trying this package. But I am getting titled error. 

```
Error running PHPCS Error: Invalid point encountered! See console for details.
    at Error (native)
    at /home/noor/.atom/packages/linter-phpcs/lib/main.js:351:19
    at Array.map (native)
    at Object.<anonymous> (/home/noor/.atom/packages/linter-phpcs/lib/main.js:325:25)
    at next (<anonymous>)
    at step (/home/noor/.atom/packages/linter-phpcs/lib/main.js:9:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)(anonymous function) @ linter-registry.js [sm]:137_tickCallback @ internal/process/next_tick.js:103
```

atom version 1.16.0
php version: PHP 7.0.15
phpcs version: PHP_CodeSniffer version 2.8.1

I have manually added the phpcs path. Path location is 
`/home/noor/.composer/vendor/squizlabs/php_codesniffer/scripts/phpcs`

**Comment by Arcanemagus** [comment]
This error is given when `phpcs` returns a point for a message that doesn't actually exist in the file. Are you able to share the file you were working on at the time (assuming it still gives you this error)?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response. The upcoming release will have a fix for tabs if you are using those in your files with certain standards.

**Comment by leewillis77** [comment]
I can confirm that I also receive this error with the following versions:

Atom: 1.16.0
linter-phpcs: 1.6.3
PHPCS: 2.8.1
PHP: 7.1.4

I'm using the WordPress-Extra standard from https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards, and the sample file at https://gist.github.com/leewillis77/40482d93ed86d3cc7111fdf5d19ff9cf produces the error for me.

The message causing the error is as follows (taken from the dev tools console):

Object
	column : 75
	fixable : true
	line : 6
	message : "Expected 1 space after closing parenthesis; found 0"
	severity : 5
	source : "Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis"
	type : "ERROR"

I can open as a new issue if that's preferable?

**Comment by Arcanemagus** [comment]
@leewillis77 Hmm, what is the full list of WordPress standards? I only added an exception for `WordPress` that fixes the setting for you automatically.

Until that gets added you can manually set the [`tabWidth` setting](https://github.com/AtomLinter/linter-phpcs/blob/v1.6.3/package.json#L69) to 4 so that it will work with that standard. If not all of your projects use that standard you can use [Project Manager](https://atom.io/packages/project-manager) in order to only set that for specific projects.

If that doesn't answer your question please file a new issue as this is a generic message when PHPCS has given an invalid point.

**Comment by leewillis77** [comment]
Hi; 

The standards include:

- WordPress
- WordPress-Core
- WordPress-Docs
- WordPress-Extra
- WordPress-VIP

I can confirm that setting the tabWidth to 4 avoids this issue.

**Comment by Arcanemagus** [comment]
I'll add all of those as automatic overrides, thanks for the list!

**Comment by drywall** [comment]
Just ran into this same situation. Setting tabWidth to 4 does, in fact, seem to resolve the issue.

**Comment by Arcanemagus** [comment]
@drywall How well tabs are handled depends both on the version of this package, and the version of PHPCS in use. If you have v1.6.6 of `linter-phpcs` _and_ PHPCS 3.0.1 then everything should work, but any version below that you might need to manually set the setting if you are using a standard other than the ones already listed as needing an override.

**Comment by drywall** [comment]
@Arcanemagus Thanks. FWIW, I'm using the WordPress-Extra standard mentioned above, with linter-phpcs 1.6.6 and phpcs 2.9.1 (the WordPress standards are [currently incompatible](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/718) with phpcs 3.x).

**Comment by Arcanemagus** [comment]
Odd, `WordPress-Extra` is [one of](https://github.com/AtomLinter/linter-phpcs/blob/dbf8863dfc9ce7ee2dcc2f3ed9b91ddb6d9015a7/lib/main.js#L55) the overridden standards, so it should be working there. I just noticed though that only overriding the default value is being tested in the specs, not letting the standard value default to overridden so maybe something is being missed in some versions.

**Comment by Arcanemagus** [comment]
Ha, just was working in some ancient PHP code today that still used tabs and found that there is a bug in the part that the specs weren't testing that I noted above 😞.

**Comment by Arcanemagus** [comment]
@drywall Can you try v1.6.7? It's possible the fixes in there solved your problem, if not please file a new issue.

**Comment by bfintal** [comment]
I'm encountering this issue also in some of my files. I'm using standards like what @leewillis77 is using plus PHPCompatibility with linter-phpcs v1.6.7 and phpcs 2.9.1.

Having the tabWidth 4 and converting all spaces to tabs works.

**Comment by Arcanemagus** [comment]
@bfintal If you are seeing this on files indented with spaces then that is a different bug in `phpcs` than the ever present tab bug. If you want to get this fixed file an issue on the PHPCS repository with some code to reproduce it.
