### ISSUE TITLE
suggest: add a setting "only check when saved"

### ISSUE THREAD

**Issue by sinkcup** [AtomLinter/linter-phpcs#264]
Now it checks when I input anything, it's too frequent, and make atom blinking.

I suggest add a setting "when to check": "saved" or "onkeyup".

**Comment by Arcanemagus** [comment]
If you check the settings for the Linter package you can find settings to disable linting on change, or to increase the delay after a change before it triggers a lint.

**Comment by sinkcup** [comment]
where? I can't find it in settings.

![image](https://cloud.githubusercontent.com/assets/4971414/26758363/4155ed9e-48a1-11e7-9d5b-fe16ec6d7510.png)

**Comment by synthetiv** [comment]
The settings you want are for the main `linter` package, not `linter-phpcs` – they're called "Lint on Change" and "Lint on Change Interval".
<img width="758" alt="screen shot 2017-06-03 at 10 19 05 pm" src="https://cloud.githubusercontent.com/assets/752281/26758392/c2c97d10-48aa-11e7-8a56-df24761cd1b0.png">
