### ISSUE TITLE
Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by yawalkar** [AtomLinter/linter-phpcs#265]
[Enter steps to reproduce:]

1. Tried editing any php files, while coding if any error is encountered, it gives me this error.

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [linter-phpcs](https://github.com/AtomLinter/linter-phpcs) package 1.6.4

### Stack Trace

Uncaught RangeError: Invalid string length

```
At /Users/nitinyawalkar/.atom/packages/linter-phpcs/node_modules/sb-exec/lib/index.js:44

RangeError: Invalid string length
    at Array.join (native)
    at /packages/linter-phpcs/node_modules/sb-exec/lib/index.js:44:34)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -0:14.7.0 application:add-project-folder (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.1 
intentions 1.1.2 
linter 2.1.4 
linter-php 1.3.2 
linter-phpcs 1.6.4 
linter-ui-default 1.2.4 
phpcbf 0.2.1 
split-diff 1.3.0 
```

**Comment by Arcanemagus** [comment]
@steelbrain Looks like this is equivalent to [this line](https://github.com/steelbrain/exec/blob/v4.0.0/src/index.js#L53), any idea how this could be crashing `Array.join`?

**Comment by steelbrain** [comment]
Hi @yawalkar

This looks like a Javascript VM limitation. It throws the error if the resulting string of `Array.join` (and similarly `JSON.stringify` among others) is too big for it to handle

For example

> I opened a very large (591.0 MB (591,032,444 bytes)) JSON file.

from https://github.com/atom/atom/issues/7417

> Today when it runs out of RAM above gives this message
> RangeError: Invalid string length

from https://github.com/nodejs/node-v0.x-archive/issues/14170

**Comment by yawalkar** [comment]
@steelbrain I was just editing the small php file having less than 1k lines of code.

**Comment by Arcanemagus** [comment]
@yawalkar Are you able to share that file and the associated PHPCS config? If not, how many errors does PHPCS report when you run it in the CLI?

**Comment by yawalkar** [comment]
This error isn't there after changing some configurations, but this issue is continue even there's no error - https://github.com/AtomLinter/linter-phpcs/issues/266

**Comment by yawalkar** [comment]
Also, I don't get any errors on circleCi for the file I was editing. Just pressing the command + s to save the file will trigger the error I reported in the new issue.

**Comment by ivanslf** [comment]
The same happened here with a 10-line file.

**Comment by Arcanemagus** [comment]
@ivanslf If you are able to share the file (and configuration!) please file a new issue, thanks!

**Comment by ivanslf** [comment]
It's an open repo. I'll do it.
