### ISSUE TITLE
Getting error message popup even theres no error

### ISSUE THREAD

**Issue by yawalkar** [AtomLinter/linter-phpcs#266]
I just updated the atom to 1.17.0 and also the linter package to 2.1.4. Now while writing the code, each time I stop writing, I get the error message popup saying to check the console for errors even there's no error. I tried changing the option to link on change, and now, on every time I save the work, I get the same error prompt link in the following screenshot -

https://cl.ly/1v2L3D1W051H

Even there's no error, I get this every time I save the work in Atom.
This was initially opened in the linter repo - https://github.com/steelbrain/linter/issues/1470
Also, there's a relative issue here - https://github.com/AtomLinter/linter-phpcs/issues/265

However, the above issue regarding the uncaught error isn't there after changing some configurations. But the error message keeps popping even there's no error.

**Comment by Fernando-Marquardt** [comment]
Could you provide the information from the console on the Developer Tools? You can press Ctrl + Alt + I to open it.

The error mentioned in the message is an internal error not a lint error in your file.

**Comment by wpdevco** [comment]
Same issue. Here are my console error messages:

![image 2017-05-24 at 6 06 26 pm](https://cloud.githubusercontent.com/assets/879872/26431751/c0f243fc-40ab-11e7-8012-b3aac668f1a5.png)

**Comment by Fernando-Marquardt** [comment]
@wpdevco Your PHP is configured to report notices (usually simple things like undefined array indexes or non declared variables being used) and this is making PHPCS to return an invalid response.

You can check your php.ini and look for the error_reporting property and change it to something else (you can take a look at the docs http://php.net/manual/pt_BR/function.error-reporting.php) or open an issue to the responsibles for the Wordpress Sniffs for them to take a look.

**Comment by Arcanemagus** [comment]
Marking this as closed due to a lack of response. If you are still having issues @yawalkar please provide the requested information 😉.
