### ISSUE TITLE
PHPCS sometimes only "sees" part of a file

### ISSUE THREAD

**Issue by synthetiv** [AtomLinter/linter-phpcs#270]
On my system, especially when I'm working on a file that's over ~1000 lines long, PHPCS will occasionally show a bunch of errors (linter errors, not JS errors) that indicate to me that it's only being sent, or is only reading, _part_ of the file, starting at the beginning.

For instance, in the screenshots below, PHPCS appears to have only "seen" up to the first `_` of a call to the `__()` function, which also happened to be in the middle of an `elseif` block in a function inside a class declaration – meaning that in addition to thinking the file ends with a `_` instead of a newline, it also thinks a bunch of `}`s are missing and that a bunch of previous lines are indented incorrectly.

<img width="876" alt="screen shot 2017-05-27 at 9 00 09 pm" src="https://cloud.githubusercontent.com/assets/752281/26525256/31eb8be2-4320-11e7-842f-96c8556ebef3.png">

The line shown above _is_ indented properly, and that's not an inline control structure – there's a `{` at the end!

<img width="1121" alt="screen shot 2017-05-27 at 9 00 30 pm" src="https://cloud.githubusercontent.com/assets/752281/26525255/31eb6ce8-4320-11e7-8cc0-bf0115c234df.png">

I _did_ use `__()`, and, well, that's not the end of the file.
After that line, the linter shows no more errors, because when it ran, PHPCS didn't know they existed.

As far as I can tell, the `phpcs` process itself isn't being interrupted, because it's still outputting properly formatted JSON that the linter package can read and display; and it's apparently exiting with a status of 1, meaning it found errors in the file, but that nothing else went wrong with it (I've tested this by throwing some console.log and debugger calls into the package code locally).

This happens mostly on large-ish files, and especially if Atom is particularly 'busy' – like if I've just opened it, or if the `remote-sync` package is uploading the file somewhere at the same time, or if I also have `linter-php` enabled, or if "lint while you type" is enabled and I've been typing a lot. I can disable those packages/features and this issue crops up less, but it isn't entirely eliminated.

There's no consistent spot in the file where it stops, as far as I can tell, and often the errors can be cleared by simply running `linter:lint` again (but sometimes the same problem pops up and I have to try again a few times).

This isn't a particularly new issue for me – I think it's been around since I started using this package a couple months ago – but since it was intermittent and I hadn't seen anyone else report anything similar, I just ignored it for a while. I've found this package really useful, though, so I'd love to get it working more consistently!

I'm running:
* **Atom:**       1.18.0-beta2
* **OS:**         Mac OS X 10.12.4
* **Misc**
    * apm  1.18.1
    * npm  3.10.10
    * node 6.9.5 x64
    * python 2.7.13
    * git 2.11.0
    * php 7.0.15

**Comment by Arcanemagus** [comment]
My only guess is that this is a bug in PHPCS that is being exposed by the more frequent running done by using this provider, especially since the JSON being returned is valid. Without steps to reproduce this I'm not sure what I can really do here unfortunately 😕.

**Comment by synthetiv** [comment]
Thanks, and I hear ya – _I_ don't even have steps to reproduce it. If I discover a reliable method I'll let you know. And you're right that a PHPCS bug, or even a bug in the coding standards I'm using, may be a more likely cause of this sort of behavior.

**Comment by synthetiv** [comment]
You were totally right, it's a PHPCS bug: squizlabs/PHP_CodeSniffer#1472

Pending an official release that fixes this, patching the copy of phpcs that I use with Atom so that it uses `stream_get_contents()` instead of a loop with `fgets()` and `usleep()` appears to have fixed this issue for me.
