### ISSUE TITLE
Not running on every file

### ISSUE THREAD

**Issue by grappler** [AtomLinter/linter-phpcs#273]
I am using `phpcs.xml.dist` in the root of my project.

I using composer to load a few other repos in the project but they are not in the `vendor` folder. These repos have their own git file and are excluded from the projects git.

Errors and warnings are shown for files in the root of the project but in the repos in the sub folder.

How can I debug why this is happening?

**Comment by Arcanemagus** [comment]
> are excluded from the projects git

It sounds like you have these files ignored in your VCS, you will need to disable the "Exclude VCS Ignored Paths" setting in Atom for linting to run on these files since Linter respects that setting.

**Comment by grappler** [comment]
Ah, thanks, that is what was causing the issue. 👍
