### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by davidbarratt** [AtomLinter/linter-phpcs#28]
This package doesn't appear to be working anymore. :(

I'm assuming this has something to do with the changes in Linter?

**Comment by BrandonDusseau** [comment]
The package appears to be working fine for me.

**Comment by steelbrain** [comment]
I think I'm gonna port this package to latest version of linter

**Comment by davidbarratt** [comment]
I'm using @AtomLinter linter `1.1.0` and linter-phpcs 0.0.15

**Comment by steelbrain** [comment]
Thanks for the info, I'm working on the upgrade to new API, should be done very soon.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-phpcs/pull/30

**Comment by davidbarratt** [comment]
@steelbrain,

Any idea why Atom isn't picking up the new release? Is there a way to force it?

**Comment by steelbrain** [comment]
You could try upgrading atom itself.

**Comment by davidbarratt** [comment]
"No update available. Version 1.0.0 is the latest version." :(

**Comment by steelbrain** [comment]
You could try a manual upgrade
```
cd ~/.atom/packages
rm -rf linter-phpcs
git clone https://github.com/AtomLinter/linter-phpcs
```
and then restart atom
