### ISSUE TITLE
Error running PHPCS Error: Invalid point encountered!

### ISSUE THREAD

**Issue by mgalvin** [AtomLinter/linter-phpcs#280]
Getting this error in the console when linting some PHP files. This causes the linter to fail and not lint a given file at all. I'm on Atom 1.18.0 and linter-phpcs 1.6.7. I'm using PHPCS 

```
phpcs --version
PHP_CodeSniffer version 2.9.0 (stable) by Squiz (http://www.squiz.net)
```

And using WordPress CS Rulesets: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

```
/Users/galvima/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running PHPCS Error: Invalid point encountered! See console for details.
    at Error (native)
    at /Users/galvima/.atom/packages/linter-phpcs/lib/main.js:356:19
    at Array.map (native)
    at Object.<anonymous> (/Users/galvima/.atom/packages/linter-phpcs/lib/main.js:330:25)
    at next (<anonymous>)
    at step (/Users/galvima/.atom/packages/linter-phpcs/lib/main.js:5:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)(anonymous function) @ /Users/galvima/.atom/packages/linter/lib/linter-registry.js:159
```

```
/Users/galvima/.atom/packages/linter-phpcs/lib/main.js:342 linter-phpcs:: Invalid point encountered in the attached message Objectmessage: Objectcolumn: 54fixable: falseline: 100message: "Found: ==. Use strict comparisons (=== or !==)."severity: 5source: "WordPress.PHP.StrictComparisons.LooseComparison"type: "WARNING"__proto__: Objectsource: ObjectlineLength: 50lineText: "				if ( $signup->domain . $signup->path == '' ) {"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()(anonymous function) @ /Users/galvima/.atom/packages/linter-phpcs/lib/main.js:342
/Users/galvima/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running PHPCS Error: Invalid point encountered! See console for details.
    at Error (native)
    at /Users/galvima/.atom/packages/linter-phpcs/lib/main.js:356:19
    at Array.map (native)
    at Object.<anonymous> (/Users/galvima/.atom/packages/linter-phpcs/lib/main.js:330:25)
    at next (<anonymous>)
    at step (/Users/galvima/.atom/packages/linter-phpcs/lib/main.js:5:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)(anonymous function) @ /Users/galvima/.atom/packages/linter/lib/linter-registry.js:159
```

This happens on different files. An example of where this happens is on the WordPress wp-activate.php file in the WordPress docroot.

[wp-activate.php.zip](https://github.com/AtomLinter/linter-phpcs/files/1097881/wp-activate.php.zip)

Please let me know if any other details are needed to work on resolving this or if there is anything else I can do to help out!

**Comment by Arcanemagus** [comment]
To attempt to reproduce this I would need your PHPCS configuration file as well as this is often an issue with the "how many spaces should a tab equal" setting.

**Comment by mgalvin** [comment]
```
phpcs --config-show installed_paths
installed_paths: /usr/local/share/php-code-sniffer/Standards,/usr/local/share/php-code-sniffer/Standards/wpcs
```

```
phpcs -i
The installed coding standards are MySource, PEAR, PHPCS, PSR1, PSR2, Squiz, Zend, WordPress, WordPress-Core, WordPress-Docs, WordPress-Extra and WordPress-VIP
```

phpcs.xml sits at the project root where Atom can see it and contains:

```
<?xml version="1.0"?>
<ruleset name="MyProjectStandard" namespace="MyProject\CS\Standard">
	<rule ref="WordPress-VIP"/>
</ruleset>
```

Tabs in Atom are set to hard tabs per WP standards and represented in UI by 2 space indenting.
<img width="1107" alt="atom tabs" src="https://user-images.githubusercontent.com/1236697/27491812-d240aafe-5811-11e7-9272-37a95597f8be.png">

Plugin settings are: 
<img width="876" alt="linter-phpcs settings" src="https://user-images.githubusercontent.com/1236697/27491877-10f66b94-5812-11e7-8f8d-0fdec8e370d1.png">


Hope that helps. Let me know if you need anything else.

**Comment by mgalvin** [comment]
And I am running this on macOS Sierra.

**Comment by jaredatch** [comment]
I'm getting this as well, but sporadically. Haven't been able to spot a trend on _why_.

**Comment by jaredatch** [comment]
What's the best way we can help debug this? On a large project I'm working on it go so bad I just had to disable PHPCS in Atom. I still haven't been able to determine a pattern.

**Comment by scottsweb** [comment]
I am also seeing very similar issues with the WordPress ruleset. Some files are OK, most are not. Issue reported as `phpcs:: Invalid point encountered in the attached message`.

Versions:
* PHP_CodeSniffer version 2.9.1 (stable) by Squiz (http://www.squiz.net)
* Atom: 1.18.0
* Ruleset same as above

Changing the default editor setting for Tab Length did fix one file I was having an issue with and then broke others.

Would love some debugging tips too

**Comment by jaredatch** [comment]
More details from an example
![image 2017-07-24 at 9 29 05 am](https://user-images.githubusercontent.com/630686/28528319-fa64084c-7052-11e7-99e5-c69c804c23ea.png)

**Comment by jaredatch** [comment]
So, any thoughts or insight on this issue? :\

**Comment by synthetiv** [comment]
@jaredatch, is "Tab Width" set to 4 in your settings for the `linter-phpcs` package? If not, try that – 4 seems to be the magic number there, at least for the WP standards, but the default is 1.

**Comment by jaredatch** [comment]
@synthetiv thanks, that appears to have resolved it - crazy!

Never would have guessed that what was needed. I'm going to reach out the the WP Coding Standards people and suggest they make a note of this in the setup instructions.

Much appreciated.

**Comment by alejandroxlopez** [comment]
I am having the same error, and I set the "Tab With" to 4, but It does not work =/

**Comment by aubreypwd** [comment]
[This(https://github.com/AtomLinter/linter-phpcs/issues/280#issuecomment-319554831) worked for me.

**Comment by kasparsd** [comment]
Would it make sense to set the default `tabWidth` to the current `atom.config.get('editor.tabLength')` instead of hard-coded `1`?

Secondly, what is the purpose of the `tab_width` setting? I couldn't find it in the commit history for the feature.

**Comment by nesmyslny** [comment]
I think it has something to do with encoding/special characters/... At least in my case.
Here's my way to reproduce this issue:

1. Have a very long line (e.g. long string); provoking `[Generic.Files.LineLength.TooLong] Line exceeds X characters; contains 454 characters` (X = your 'Preferred Line Length' setting)
2. Add some characters with accents, e.g. `éí` (in this case both characters are needed to get the error)
3. -> The error shows up on every change and on save

I used this line to reproduce the error (make sure to include the last two characters of the string):
```php
$s = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.éí';
```

**Comment by jaredatch** [comment]
All I know is before I was using Atom, I was on Sublime Text 3 and never had to set tab width settings with PHPCS linting.

After using Atom, I switched to Visual Code Studio, where there are no tab width settings, it just works.

**Comment by lilolbear** [comment]
Similar situation with PSR2 being the standard and setting the linter-phpcs package "Tab Width" from unset default of 1 to 4 and having the issue resolve itself. Thanks for the hack @synthetiv. 
+1

**Comment by nelson6e65** [comment]
> @jaredatch, is "Tab Width" set to 4 in your settings for the `linter-phpcs` package? If not, try that – 4 seems to be the magic number there, at least for the WP standards, but the default is 1.

Thanks. This solves my problem too. :smiley:


---
From creators of _**"Nightmares of missing `;`s"**_ some years ago... Now comes _**"Nightmares of the tab width not configured to `4`"**_ :sweat_smile:

**Comment by Skeeve** [comment]
Setting the tab-width to 4 using Joomla CS did not help me.

My line is 149 characters long, the first 2 being tabs, linter-phpcs reports that the error is in column 154.

**Comment by sjuvonen** [comment]
It's got nothing to do with tab width, most likely all these guys are breaking their linters by misconfiguring it to detect line lengths wrong. (Why this setting is needed? Seems like existence of the setting is a bug in itself.)

The reason is that phpcs does not support unicode and miscounts number of characters on a line when there are multibyte Unicode characters. Linter-phpcs itself gets the right character count which is less than what phpcs's ASCII-based counter gives.

The fix is to make linter-phpcs use byte count instead of character count as line length. 

```let byteCount = Buffer.byteLength(editorLine.text)```

Something like that, I don't know about Atom internals.

**Comment by UziTech** [comment]
Closing this as stale. If this is still an issue for anyone we can reopen it.
