### ISSUE TITLE
PHP process timeout not working since Atom 1.18.0

### ISSUE THREAD

**Issue by mundschenk-at** [AtomLinter/linter-phpcs#282]
It appears that since the update to Atom 1.18.0, a variant of #239 is rearing its head again. The PHP processes don't timeout anymore (and killing them manually will freeze the AtomHelper process).

macOS Sierra 10.12.5

**Comment by Arcanemagus** [comment]
Unfortunately I've never been able to reproduce this, so I have no way to test this. The code should be calling `kill()` on the child `php` processes, my guess is that something on your OS is preventing that from fully killing the process.

I'm not even sure how to debug this further...

**Comment by mundschenk-at** [comment]
I've looked around at the code an the problem seems to be the five minute timeout set in https://github.com/AtomLinter/linter-phpcs/blob/master/lib/main.js#L277

I've patched my installation to change this back to 10 seconds and things work much more smoothly now.

**Comment by Arcanemagus** [comment]
That timeout is a bit misleading, the `uniqueKey` parameter tells `exec` to only allow one process to be running for that key at a time. So you should have at most one `phpcs` running per open PHP file.

The timeout that you modified there is when it should automatically kill the process whether or not there is another one running. Are you saying that you were having multiple running for the same file?

**Comment by mundschenk-at** [comment]
I'd have to check if it was actually multiple php processes. However, very often the processes ran for the whole five minutes and the editor became unresponsive. Shortening the timeout results in bad parser results about 50 percent of the time (with relatively large PHP files), but at least the editor stays usable. Running `phpcs` from the command line has no such problems (i.e. it does not take "forever" for a single file).

**Comment by Arcanemagus** [comment]
The fact that `phpcs` runs differently is a phpcs bug, nothing that can be done about that here unfortunately.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response. Please let me know if you are still seeing this.

**Comment by mundschenk-at** [comment]
It seems to have been fixed in recent versions, either of phpcs or the Atom libraries.
