### ISSUE TITLE
Error parsing PHPCS response

### ISSUE THREAD

**Issue by elzette** [AtomLinter/linter-phpcs#283]
Hello
I am trying to set up this linter with WordPress coding standards. 
I am getting an error but not any info in Console. Not sure what to do or where I've missed something. 
I have attached a screenshot showing the error with what is showing in Console (not much).
Also a screenshot of the settings. 
I realise this is probably not an issue with linter-phpcs, but if someone have any ideas on the issue I am having it would be much appreciated. 
![screen shot 2017-06-28 at 11 31 30](https://user-images.githubusercontent.com/2685390/27633153-fc34b7dc-5bf5-11e7-9dd6-c65e4c8f36cd.png)
![screen shot 2017-06-28 at 11 01 12](https://user-images.githubusercontent.com/2685390/27633166-0a2363b6-5bf6-11e7-98ee-f47b66e4bc3d.png)

**Comment by jrsinclair** [comment]
Also getting this issue :(

**Comment by synthetiv** [comment]
Does PHPCS work from the command line? What happens when you run it on one of the PHP files you're trying to lint in Atom, with `phpcs --standard=WordPress your-filename-here.php`?

**Comment by elzette** [comment]
Thanks for asking. 
I ran that command line. Trying one of the files. Nothing happens. Like there is no reaction.

**Comment by joneslloyd** [comment]
I have exactly the same situation as @elzette -- I ran it via command line (`phpcs --standard=WordPress-VIP /Users/joneslloyd/files/path/myfile.php`) and nothing happens in the terminal

**Comment by synthetiv** [comment]
Yep, the version number was going to be my next question – the WP standards don't yet support PHPCS 3.0. One day it will – see WordPress-Coding-Standards/WordPress-Coding-Standards#718 – but until then, you'll need to stick to using PHPCS 2.x.

**Comment by joneslloyd** [comment]
Ah-ha! Right! Thanks for this info!

Totally off-topic, but do you know how I can downgrade phpcs to 2.x.? (I installed via composer)

**Comment by elzette** [comment]
I was on PHPCS 3.0, also installed with composer, but reverted back @joneslloyd using `composer global require "squizlabs/php_codesniffer=^2.9.0"` (@JDGrimes was kind to help me with that). 
I was thinking the version is not the issue in my case.

**Comment by joneslloyd** [comment]
Thanks for the additional info -- For me, this has sorted things

**Comment by synthetiv** [comment]
Hmm. @elzette, could it be that linter-phpcs is still configured to use the old 3.0.0 binary instead of the 2.9.x one you installed?

**Comment by elzette** [comment]
Erm... possibly. Is there a way to check that. Or a way to just start all over with all of the installations?

**Comment by synthetiv** [comment]
Now that I remember what you said earlier (that it doesn't work on the command line either), I guess it's not just an Atom config issue. But you can see what version you're running on the command line by running `phpcs --version`.

**Comment by elzette** [comment]
Strange, I get `PHP_CodeSniffer version 2.8.1 (stable)`

**Comment by YewTreeWeb** [comment]
this also solved my issue for me, with rolling back to phpcs 2.9.1

**Comment by YewTreeWeb** [comment]
Hi @elzette, what php environment are you running? I had an issue when I was using an MAMP environment. To fix it I had to make an alias in my bash_profile pointing to MAMP's php.

This may not help but if you are running MAMP then it could be worth a try as it helped me.

**Comment by synthetiv** [comment]
Seems worth a mention that the next release of the WP coding standards is coming out at the end of this week, and it will finally support PHPCS 3.x. Perhaps a clean install of both PHPCS and WPCS could help with the problems folks are reporting in this thread.

**Comment by mattschinkel** [comment]
I have the same issue. When I run phpcs c:/temp/myfile.php I get 

----------------------------------------------------------------------
FOUND 2 ERRORS AND 5 WARNINGS AFFECTING 7 LINES
----------------------------------------------------------------------
  1 | ERROR   | [x] End of line character is invalid; expected "\n"
    |         |     but found "\r\n"
 11 | ERROR   | [ ] You must use "/**" style comments for a file
    |         |     comment
 15 | WARNING | [ ] Line exceeds 85 characters; contains 122
    |         |     characters
 50 | WARNING | [ ] Line exceeds 85 characters; contains 156
    |         |     characters
 59 | WARNING | [ ] Line exceeds 85 characters; contains 148
    |         |     characters
 60 | WARNING | [ ] Line exceeds 85 characters; contains 157
    |         |     characters
 65 | WARNING | [ ] Line exceeds 85 characters; contains 92
    |         |     characters
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 389ms; Memory: 5.75Mb

**Comment by UziTech** [comment]
Closing this as stale. If this is still an issue for anyone we can reopen it.
