### ISSUE TITLE
Falsely error with docblock indentation

### ISSUE THREAD

**Issue by distantnative** [AtomLinter/linter-phpcs#284]
I have a project based on PSR2 with code as follows:

```php
<?php

namespace Kirby\Toolkit;

/**
 * Collection
 *
 * @license   MIT
 */
class Collection implements \Countable
{

    public $data = [];

    /**
      * Constructor
      *
      * @param array $data
      */
```

As you can see it uses the typical PHP docblock indentation, where from the second comment line on the lines are indented one additional space to match the column of `*`. 

But when I do this, all PHP parts are throwing this linting error about false indentation:
<img width="823" alt="screen shot 2017-07-07 at 10 15 06" src="https://user-images.githubusercontent.com/3788865/27949223-2f6bb868-62fd-11e7-8c18-5e538dc20f23.png">

How can I fix this? Is this a wrong setting or a bug?

**Comment by Arcanemagus** [comment]
Do you see the same results when running `phpcs` on the CLI?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
