### ISSUE TITLE
Appears to crash Windows 7 explorer.exe when saving a PHP file

### ISSUE THREAD

**Issue by Torniojaws** [AtomLinter/linter-phpcs#285]
I have only noticed this happening when working on some PHP files. At least once a day, explorer.exe crashes, always when I save a PHP file in Atom (version 1.18.0 ia32) with linter-phpcs (version 1.6.7) enabled.

If I work on the same files with linter-phpcs disabled, I have yet to see such crashes. Also, no other linter (eg. Python linter, JSX linter, etc) in Atom has crashed explorer.exe.

Specifics:
- Windows 7 64-bit
- Atom version 1.18.0 ia32
- linter-phpcs version 1.6.7
- PHP version 5.6.19
- I edit the repo in Windows with Atom, but the project runs inside Vagrant (ubuntu/trusty32) in Apache 2 with PHP 5.5.9
- The same Vagrant setup is used when I do Python work (no crashes)

The PHP file contents don't really matter - I have seen crashes from both bigger files and even from just plain skeletons (nothing defined inside the class):
```
<?php

namespace My\Test;

class Example
{

}
```

I have these packages enabled in Atom:
atom-beautify 0.29.18
autocomplete-python
autoupdate-packages 1.3.1
busy-signal 1.4.3
file-watcher 1.1.0
intentions 1.1.2
linter 2.2.0
linter-eslint
linter-flake8 2.1.5
linter-pep8 1.3.2
linter-phpcs 1.6.7
linter-pycodestyle 2.0.2
linter-ui-default 1.6.2
path-copy 0.14.0
python-indent 1.1.0
python-tools 0.6.9
react 0.16.2
select-rectangle 1.0.2

**Comment by Arcanemagus** [comment]
Hmmm, phpcs can sometimes leave `php.exe` processes running for a while, my only guess is that that's somehow causing this? Without more information to narrow down where the problem is happening I'm afraid there isn't much I can do to help 😞.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
