### ISSUE TITLE
helpers.exec does not run as expected

### ISSUE THREAD

**Issue by RodrigoBalest** [AtomLinter/linter-phpcs#289]
Hi!

I'm getting the following error:
![error](https://user-images.githubusercontent.com/4810463/30219116-762e231a-9491-11e7-9c8c-fbf0d43c0f43.png)

This is the console output:
![log](https://user-images.githubusercontent.com/4810463/30219280-f4e9b156-9491-11e7-969a-7fa35a1fe7ab.png)

So I logged the output of the line that tries to get phpcs' version at `linter-phpcs/lib/main.js:36`, as follows:
![code](https://user-images.githubusercontent.com/4810463/30219902-ee641ca2-9493-11e7-8619-ed87b77a59db.png)

And this is what I got:
![log2](https://user-images.githubusercontent.com/4810463/30219909-f75abd52-9493-11e7-9809-2d2fd52644b2.png)

It seems `helper.exec` method is not sending the `--version` option, so `phpcs` is running without parameters.

I'm using linter-phpcs v1.6.7 with Atom v1.19.7 on Windows 7.

**Comment by Arcanemagus** [comment]
That's... quite bizarre, and I'm unable to reproduce. What version of `phpcs` are you running? This package supports versions 1.3.0 RC1 and up, although it's not even possible to install versions below 1.4.2 through `composer`...

**Comment by RodrigoBalest** [comment]
I had downloaded phpcs from github.

Now I installed phpcs from pear, and it worked.

I think the failure was because pear sets the correct path to php executable on phpcs.phar file upon installation, which was wrong on downloaded version of phpcs.phar.

I tried to directly set the php executable path on the downloaded phpcs.phar file, but then it complained about "wrong file hash", so the best solution I found was to install it through pear.

**Comment by Arcanemagus** [comment]
Just as an FYI: Windows can't execute `*.phar` files directly, you need a wrapper script to be able to call them normally. What `pear` did was create this wrapper script for you and place it in a location that was added to your `%PATH%`.
