### ISSUE TITLE
Error running PHPCS Error: The system cannot find the path specified.

### ISSUE THREAD

**Issue by vinit-thoughti** [AtomLinter/linter-phpcs#290]
Everytime I open a PHP file in Atom, it shows an error saying 'Error running PHPCS'. In console I see following error

> [Linter] Error running PHPCS Error: The system cannot find the path specified.
>     at ChildProcess.<anonymous> (C:\Users\Admin\.atom\packages\linter-phpcs\node_modules\sb-exec\lib\index.js:56:20)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:885:16)
>     at Socket.<anonymous> (internal/child_process.js:334:11)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at Pipe._handle.close [as _onclose] (net.js:501:12)
>     at promises.push.Promise.then._this2.emitter.emit.number (file:///C:/Users/Admin/.atom/packages/linter/lib/linter-registry.js:101:37)
>     at _loop (file:///C:/Users/Admin/.atom/packages/linter/lib/linter-registry.js:99:21)
>     at LinterRegistry.<anonymous> (file:///C:/Users/Admin/.atom/packages/linter/lib/linter-registry.js:87:40)
>     at Generator.next (<anonymous>)
>     at LinterRegistry.<anonymous> (file:///C:/Users/Admin/.atom/packages/linter/lib/linter-registry.js:143:4)
>     at Generator.next (<anonymous>)
>     at step (C:\Users\Admin\.atom\packages\linter\lib\linter-registry.js:5:273)
>     at C:\Users\Admin\.atom\packages\linter\lib\linter-registry.js:5:443
>     at LinterRegistry.<anonymous> (C:\Users\Admin\.atom\packages\linter\lib\linter-registry.js:5:99)
>     at file:///C:/Users/Admin/.atom/packages/linter/lib/main.js:125:30
>     at Function.module.exports.Emitter.simpleDispatch (C:\Users\Admin\AppData\Local\atom\app-1.19.6\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
>     at Emitter.module.exports.Emitter.emit (C:\Users\Admin\AppData\Local\atom\app-1.19.6\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
>     at EditorLinter.lint (file:///C:/Users/Admin/.atom/packages/linter/lib/editor-linter.js:40:18)
>     at EditorRegistry.createFromTextEditor (file:///C:/Users/Admin/.atom/packages/linter/lib/editor-registry.js:43:20)
>     at file:///C:/Users/Admin/.atom/packages/linter/lib/editor-registry.js:25:12
>     at C:\Users\Admin\AppData\Local\atom\app-1.19.6\resources\app\src\workspace.js:721:22
>     at Function.module.exports.Emitter.simpleDispatch (C:\Users\Admin\AppData\Local\atom\app-1.19.6\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
>     at Emitter.module.exports.Emitter.emit (C:\Users\Admin\AppData\Local\atom\app-1.19.6\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
>     at C:\Users\Admin\AppData\Local\atom\app-1.19.6\resources\app\src\workspace.js:594:34
>     at C:\Users\Admin\AppData\Local\atom\app-1.19.6\resources\app\src\workspace.js:595:19
>     at Function.module.exports.Emitter.simpleDispatch (C:\Users\Admin\AppData\Local\atom\app-1.19.6\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
>     at Emitter.module.exports.Emitter.emit (C:\Users\Admin\AppData\Local\atom\app-1.19.6\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
>     at PaneContainer.didAddPaneItem (C:\Users\Admin\AppData\Local\atom\app-1.19.6\resources\app\src\pane-container.js:270:24)
>     at Pane.module.exports.Pane.addItem (C:\Users\Admin\AppData\Local\atom\app-1.19.6\resources\app\src\pane.js:553:22)
>     at Pane.module.exports.Pane.activateItem (C:\Users\Admin\AppData\Local\atom\app-1.19.6\resources\app\src\pane.js:489:20)
>     at Workspace.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-1.19.6\resources\app\src\workspace.js:1161:20)
>     at Generator.next (<anonymous>)
>     at step (C:\Users\Admin\AppData\Local\atom\app-1.19.6\resources\app\src\workspace.js:11:279)

My PHPCs version is as follows :
```
C:\Windows\system32>phpcs --version
PHP_CodeSniffer version 2.9.0 (stable) by Squiz (http://www.squiz.net)
```

When I installed and configured it at starting, it was working well, but now when I am opening new PHP files, it is showing me this error.

Thanks,
Vinit

**Comment by Arcanemagus** [comment]
What do you get from running `where.exe phpcs`? Do the errors stop if you place the output of that in the "Executable Path" setting?

**Comment by vinit-thoughti** [comment]
That helped. Thank you.
