### ISSUE TITLE
Process execution timed out

### ISSUE THREAD

**Issue by deathart** [AtomLinter/linter-phpcs#291]
[Linter] Error running PHPCS Error: Process execution timed out
    at C:\Users\death\.atom\packages\linter-phpcs\node_modules\sb-exec\lib\index.js:89

**Comment by Arcanemagus** [comment]
The only way this could have triggered is if you are on an older version of this package, or `phpcs` took longer than _5 minutes_(!) to run. Can you double check that you are on v1.6.7?

**Comment by deathart** [comment]
Yes I use version 1.6.7, and I have the notification directly when I save my file

Excuse for my english i use google traduction

**Comment by UziTech** [comment]
Closing this as stale. If this is still an issue for anyone we can reopen it.
