### ISSUE TITLE
Run with docker

### ISSUE THREAD

**Issue by bertoni** [AtomLinter/linter-phpcs#299]
Is it possible to use it with a phpcs inside a docker container? Such as the command "docker run --rm -i image/phpcs phpcs"?
I already tried, but without success...

**Comment by Arcanemagus** [comment]
You would have to create a wrapper script that passes on the arguments and `stdin` to the `docker` instance, this is not a supported setup directly here, but I'm sure others would be interested if you manage to get it working 😉.

**Comment by bertoni** [comment]
The RubberDuck always works!

I created a small script that makes a proxy to container docker:
```
#[phpcs.sh]
#!/bin/bash

PHPCS_BIN='docker run --rm -i -v /var/www/:/var/www abertoni/phpcs phpcs'
$PHPCS_BIN $@
exit $?
```
With this, enough go to the atom plugin and specify the full path of the script.

Don't forget to give permission for script: `chmod a+x phpcs.sh`

I hope it helps others friends!

**Comment by aronwolf90** [comment]
docker exec -i <container> rubocop solved the problem for me. with 

working_dir: $PWD
volumes:
  .:$PWD

in my docker-compose.overwrite.yml
