### ISSUE TITLE
Error running PHPCS Error

### ISSUE THREAD

**Issue by gabriel88d** [AtomLinter/linter-phpcs#302]
```
[Linter] Error running PHPCS Error: Failed to spawn command `phpcs`. Make sure `phpcs` is installed and on your PATH
    at /Users/lgdeloss/.atom/packages/linter-phpcs/node_modules/atom-linter/lib/helpers.js:130:24
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by Arcanemagus** [comment]
Make sure that `phpcs` has been installed. `which phpcs` should return the path to it if things are setup properly 😉.

**Comment by gabriel88d** [comment]
It was installed. I installed through atom




On Tuesday, November 28, 2017, 3:54 PM, Landon Abney <notifications@github.com> wrote:


Make sure that phpcs has been installed. which phpcs should return the path to it if things are setup properly 😉 .

**Comment by Arcanemagus** [comment]
This package (`linter-phpcs`) is just a wrapper around the `PHP_CodeSniffer` utility. You need to follow their [installation instructions](https://github.com/squizlabs/PHP_CodeSniffer#installation) in order to have it available on your system.

**Comment by gabriel88d** [comment]
Yeah, so I have followed the instructions and I'm still getting the same error, Ive gone as far as uninstalling and re-installing atom
    On Tuesday, November 28, 2017, 4:00:56 PM CST, Landon Abney <notifications@github.com> wrote:  
 
 
This package (linter-phpcs) is just a wrapper around the PHP_CodeSniffer utility. You need to follow their installation instructions in order to have it available on your system.

**Comment by Arcanemagus** [comment]
What does `which phpcs` return?

**Comment by ScarletPonytail** [comment]
I have the same issue. I have it installed in my Documents folder (Mac). Does the directory for PHPCodeSniffer matter?

**Comment by ScarletPonytail** [comment]
![image](https://user-images.githubusercontent.com/10756279/42936074-17cdc01a-8b43-11e8-86b2-4f6b39397f9c.png)

![image](https://user-images.githubusercontent.com/10756279/42936158-47f4953e-8b43-11e8-8b0e-27f9f13205a0.png)

**Comment by Arcanemagus** [comment]
@ScarletPonytail you should be getting a different error with that setting, are you sure you are seeing the _exact_ same text?

**Comment by ScarletPonytail** [comment]
@Arcanemagus Here is my Atom config:

![image](https://user-images.githubusercontent.com/10756279/42991938-099ec9c8-8bff-11e8-92b1-e4cf820ef298.png)

...and here is the Console error: 

![image](https://user-images.githubusercontent.com/10756279/42991968-26e519ce-8bff-11e8-990f-037da517f958.png)

Thanks.

**Comment by Arcanemagus** [comment]
Please create a new issue, as that is something different. When creating the issue please include the output of running `/Users/lpercival/PHP_CodeSniffer/bin/phpcs --version`, thanks!

**Comment by StephanSchrade** [comment]
Looks liek the same problem discussed here
https://github.com/AtomLinter/linter-phpcs/issues/305
and here
https://github.com/AtomLinter/linter-phpcs/issues/307

**Comment by Arcanemagus** [comment]
Closing due to a lack of response from @gabriel88d. As pointed out by @StephanSchrade you are likely hitting the same thing as #305 @ScarletPonytail.

**Comment by ThiBruning** [comment]
pá

**Comment by matheus0608** [comment]
eu tive o mesmo problema, era variaveis do sistema no windows que estava errada
