### ISSUE TITLE
Doesn't work unless opening a single file outside a project

### ISSUE THREAD

**Issue by wpdevco** [AtomLinter/linter-phpcs#303]
This is infuriating as it worked perfectly yesterday. Now, no matter what I do, it does not work unless I open a file that is outside the current project.

I even completely uninstalled Atom and phpcs to no avail.

![screen recording 2017-12-03 at 05 19 pm](https://user-images.githubusercontent.com/879872/33532402-408d7df4-d84e-11e7-8aad-94604b9ead16.gif)

**Comment by Arcanemagus** [comment]
Those aren't the same files (Project is `gmbeta`, single file is `gmb`). If you add `gmb/app/public` as a project then open `wp-activate.php` from there does it work?

**Comment by wpdevco** [comment]
>Those aren't the same files (Project is gmbeta, single file is gmb)

Yes, that's my point. Files in the project do not get linted. Any files I open _outside_ of a project, do.

**Comment by wpdevco** [comment]
Welp, figured this out. I never noticed this before but apparently if files are ignored in the `.gitignore` for a project those files will not lint when the project is open (but will if a single file is opened outside a project).

Seems great to me but not sure if this is expected behavior so I'll leave this open for you all to determine that.

**Comment by Arcanemagus** [comment]
Ah ha! Sorry, should have had you run the `Linter: Debug` command at the start which would have told us this right away.

`linter` follows Atom's global "Ignore VCS Ignored Files" setting for whether or not to ignore files that your VCS is ignoring.

Thanks for posting back with the resolution!

**Comment by Dadibom** [comment]
I've got the same issue. It worked ONCE for the file in my project, then i switched to another tab and never got it working again. No errors in the JS console. Works for files from other projects. My source files are _not_ ignored.

Platform: linux
Atom Version: 1.23.3
Linter Version: 2.2.0
Opened file is ignored: No
Matching Linter Providers: 
  - PHPCS
Disabled Linter Providers: 
Standard Linter Providers: 
  - ESLint
  - PHPCS
Indie Linter Providers: 
UI Providers: 
  - Linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - text.html.php
  - meta.embedded.block.php
  - source.php
  - string.quoted.double.php
  - punctuation.definition.variable.php

**Comment by Dadibom** [comment]
Ignore my comment, I had added a sample phpcs.xml.dist file that basically hid everything.
