### ISSUE TITLE
WPCS: Invalid point encountered in the attached message 

### ISSUE THREAD

**Issue by grappler** [AtomLinter/linter-phpcs#306]
#280

I get an error when I have the sniff `WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound` enabled.

The message is `"Hook names invoked by a theme/plugin should start with the theme/plugin prefix. Found: "content-types.post-types"."`

The code is 
```php
return apply_filters(
	'content-types.post-types',
	[
		PostType\Post::NAME             => PostType\Post::class,
	]
);
```

It should be sufficient to add `<rule name="WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound"/>` to the phpcs config file.

The sniff can be found in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

I am running Atom(1.23.3) and linter-phpcs(v1.6.8) .

**Comment by computamike** [comment]
I had the same issue - I found that the linter was using a tab spacing of 1, whereas the editor was using a tab spacing of 4.  Setting the tabspacing (in linter config) to 4 (matching the editor configuration) resolved the issue.  A better fix might be to default the tab width setting on linter to match the editor configuration.

**Comment by UziTech** [comment]
Closing this as stale. If this is still an issue for anyone we can reopen it.
