### ISSUE TITLE
I can not make work, inter-phpcs

### ISSUE THREAD

**Issue by madvik** [AtomLinter/linter-phpcs#307]
I install phpcs with composer.

I find it in this directory : 
`C:\Users\Utilisateur\AppData\Roaming\Composer\vendor\squizlabs\php_codesniffer\bin\`

In setting, here the path:
![image](https://user-images.githubusercontent.com/3822529/35646590-f1ec143e-06cf-11e8-9ccb-50c2c3edeab1.png)

The error:
![image](https://user-images.githubusercontent.com/3822529/35646409-7232596a-06cf-11e8-8b50-1afadc2a1045.png)

If in the path, i not put the bat file. I have an error to:
![image](https://user-images.githubusercontent.com/3822529/35646688-4677c228-06d0-11e8-8038-4a985aa6ffd1.png)

**Comment by rsau** [comment]
Have you tried phpcs in project instead of global context?

**Comment by StephanSchrade** [comment]
Looks like the same problem discussed here:
https://github.com/AtomLinter/linter-phpcs/issues/305

**Comment by Arcanemagus** [comment]
Closing due to a lack of response from @madvik. (and potential duplicate)
