### ISSUE TITLE
Config file (phpcs.xml) is never used

### ISSUE THREAD

**Issue by pfefferle** [AtomLinter/linter-phpcs#31]
It seems that the config file is never used, because `standard` is always set with the settings or default value (PSR-2). The next problem is, that you always use the class attribute `@standard`, that's why all the logic here https://github.com/AtomLinter/linter-phpcs/blob/master/lib/main.coffee#L64 (depending the config file) is useless.

I think the custom file should always overwrite the default.

**Comment by steelbrain** [comment]
Right!

**Comment by pfefferle** [comment]
Thanks for the fast fix!

...but the second problem still isn't fixed. You always load the class-attribute `@standard` instead of the 'local' var `standard`:

```JavaScript
if standard then parameters.push("--standard=#{@standard}")
```

should be:

```JavaScript
if standard then parameters.push("--standard=#{standard}")
```

**Comment by steelbrain** [comment]
Done, Thanks :)

**Comment by pfefferle** [comment]
Thanks again for the fast fix, everything works fine now :)
