### ISSUE TITLE
[Linter] Error running PHPCS Error: spawn EACCES

### ISSUE THREAD

**Issue by MatTeague** [AtomLinter/linter-phpcs#312]
Hi,

I updated linter-phpcs to point to phpcs and wpcs, which I had reinstalled with composer. Everything was working fine but now I'm gettings an error.

I open the developer console and the console error displayed is:

```
[Linter] Error running PHPCS Error: spawn EACCES
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:390:9)
    at /Users/mathewteague/.atom/packages/linter-codeclimate/node_modules/sb-exec/lib/index.js:24:53
    at Promise (<anonymous>)
    at /Users/mathewteague/.atom/packages/linter-codeclimate/node_modules/sb-exec/lib/index.js:23:12
    at Generator.next (<anonymous>)
    at step (/Users/mathewteague/.atom/packages/linter-codeclimate/node_modules/sb-exec/lib/index.js:146:191)
    at /Users/mathewteague/.atom/packages/linter-codeclimate/node_modules/sb-exec/lib/index.js:146:361
    at <anonymous>
```

I've got codeclimate installed but I uninstalled the linter from Atom. I've tried looking for the atom package and definitely can't find it. So I reinstalled the package but the error still occurs.

I'm using PHP 7.1 with homebrew and added `process.env.PATH = ["/usr/local/bin", process.env.PATH].join(":")`, I also tried it with the homebrew path. But the issue again still occurs.

Any help would be really appreciated.

Thanks

**Comment by Tawreh** [comment]
I have had the same problem. I'm running a Drupal site, with phpcs as a Composer dependency. 

Unchecking "Search for executables" resolved this issue (it was using the version in the repository).

**Comment by UziTech** [comment]
Closing this as stale. If this is still an issue for anyone we can reopen it.
