### ISSUE TITLE
locate failiure

### ISSUE THREAD

**Issue by brothman01** [AtomLinter/linter-phpcs#321]
Hello I have been using linter-phpcs successfully  to lint my php in atom for a long time.  Although I have been using linter-phpcs for a few years, it has suddenly stopped linting my code and I am unsure why.

I have not been able to find any documentation or directions pointing me towards commands to run or logs to check to see which parts of phpcs are working, and more importantly see which step the linter stops working.  How do I check where the failure with my phpcs starts?

**Comment by Arcanemagus** [comment]
Are you using `linter` or `atom-ide-ui`? If you are using `linter`, can you run `Linter: Debug` from the Command Palette and check the list of "Matching Providers"?

**Comment by brothman01** [comment]
@ Arcanemagus 😁

**Comment by Arcanemagus** [comment]
Hmmm, at least from that diagnostic it _should_ be triggering it. Can you open Atom's Developer Tools, place a breakpoint somewhere in the `lint` function, such as here:
https://github.com/AtomLinter/linter-phpcs/blob/4e88b9898d69a7f8d46e3cd83b960e52a839089b/lib/main.js#L193

And then open a PHP file and save it? You _should_ be stopped on the breakpoint.

**Comment by mackensen** [comment]
I ran into this issue and followed the used the breakpoints to identify at least one issue. It does execute the sniffs correctly, but the results are stored under the short name for the file (e.g. `foo/bar`), while the code is trying to use `fileRealPath`, which generates the fully-qualified path, to return the key. What's odd is that if I delete my local `.phpcs.xml.dist` linter-phpcs works as expected. I don't have any symlinks in play, and I'm running PHPCS 3.3.2.

**Comment by codiceovvio** [comment]
Thanks a lot!!
I was with the same issue after upgrading,
currently with Atom 1.38.2 on Linux Ubuntu 16.04.
Removed
`<arg name="basepath" value="./"/>`
from phpcs.xml and got it running again
:smile: :raised_hands:

**Comment by UziTech** [comment]
Closing this as stale. If this is still an issue for anyone we can reopen it.
