### ISSUE TITLE
Not Executing

### ISSUE THREAD

**Issue by davidbarratt** [AtomLinter/linter-phpcs#36]
Well I'm not getting any errors any more, but I noticed it's also not executing.

Atom 1.0.2
Linter 1.2.3
Linter PHPCS 1.0.3
PHP_CodeSniffer 2.3.2

I opened a file I know does not meet coding standards at Atom continously reports no issues. I tried changing the coding standard, restarting Atom, reinstalling Linter and Linter PHPCS, reinstalling Atom but none of that worked. :(

**Comment by steelbrain** [comment]
Did it work for you before the upgrade?

**Comment by davidbarratt** [comment]
@steelbrain,

No it didn't, see #28 and #33. It looks like I'm back to #28 (no errors, but not working either).

When I first installed it (before Atom 1.0) it worked perfectly. Although, I believe it was an upgrade to Linter that broke it for me. I could try downgrading Linter and see if that fixes it (if that would help you).

**Comment by steelbrain** [comment]
Great, let me know if it's a linter thing.

**Comment by davidbarratt** [comment]
ok, I deleted all of the atom files on the Mac and re-installed Atom from scratch and that fixed the execution problem, but now I"m getting a syntax error with a custom standard #37
