### ISSUE TITLE
 Error parsing PHPCS response - PHPCS Response ERROR: the "WordPress" coding standard is not installed.

### ISSUE THREAD

**Issue by nightshiftnights** [AtomLinter/linter-phpcs#369]
Having an issue with using WPCS. When I try to run the linter I get the popup "Error parsing PHPCS response." DevTools console then tells me "PHPCS Response ERROR: the "WordPress" coding standard is not installed. The installed coding standards are Zend, MySource, PEAR, PSR2, PSR12, PSR1 and Squiz" however running phpcs -i in terminal shows that WPCS is installed, running the lint from the terminal on the same file runs without an issue.

PHPCS version 3.3.2
PHP version 7.2.11-2+0~20181015120801.9+stretch~1
linter version 2.2.0
linter-phpcs version 1.6.11
Atom 1.32.0 x64
All runing on Debian 9.5

**Comment by UziTech** [comment]
Closing this as stale. If this is still an issue for anyone we can reopen it.
