### ISSUE TITLE
Error parsing PHPCS response

### ISSUE THREAD

**Issue by tanmalik786** [AtomLinter/linter-phpcs#375]
This is what I see in atom ..
`Something went wrong attempting to parse the PHPCS output.`

I have all the extensions installed, BUT am still unable to get rid of this error though have removed and re-installed this and other suggested extensions several times during last about 3 Hrs or so.

**Comment by kurtschlatzer** [comment]
This is still and issue.

**Comment by nextgenthemes** [comment]
There are various errors this extension stroked on. One example is this: This has been going on for years now.

`./vendor/bin/phpcs .
ERROR: Referenced sniff "Squiz.CommentedOutCode.Found" does not exist

Run "phpcs --help" for usage information
`

**Comment by chimit** [comment]
Have the same issue.

**Comment by chimit** [comment]
In my case the problem was in a wrong `phpcs.xml` file in my project which referred to another missing config file. Atom linter doesn't give you any details about the problem. Just a message "Error parsing PHPCS response". VS Code gave me a clue.

**Comment by UziTech** [comment]
Closing this as stale. If this is still an issue for anyone we can reopen it.
