### ISSUE TITLE
Error: spawn phpcs ENOENT

### ISSUE THREAD

**Issue by dougfelton** [AtomLinter/linter-phpcs#39]
linter-phpcs was working fine up until about a week ago, when it stopped working and started giving this error:

spawn phpcs ENOENT
Error: spawn phpcs ENOENT
  at exports._errnoException (util.js:734:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)

I am running:
linter-phpcs 1.0.5
PHP_CodeSniffer 2.3.3
Windows 7 Professional 64-bit

**Comment by steelbrain** [comment]
That's a node js error, it means that `phpcs` binary was not found in your `$PATH`

**Comment by dougfelton** [comment]
Thanks for the quick response.  More info:

1) I did just check, and the phpcs binary is in my `$PATH`

2) That got me thinking, so in the linter-phpcs Settings window I added the phpcs binary path to the "Executable Path" (it was empty previously) and restarted Atom.  The error no longer appears, but I'm not getting any of the visual indicators in my code that linter-phpcs is doing anything

3) Perhaps there is some confusion on my part about the "Executable Path" and the "Phpcs Executable Path" settings in the Settings window for linter-phpcs.  What is the difference between those two settings, and are they always both set or just one or...?

**Comment by steelbrain** [comment]
Ah, I think you may have some old settings that haven't been cleared after the update.
Also what's the value of `process.env.PATH` (dump it in your dev tools), does it containt that executable path?

**Comment by dougfelton** [comment]
The value of `process.env.PATH` does indeed contain that executable path.  I just tried an uninstall and reinstall of linter-phpcs and the two executable path input boxes in "Settings" are still there.

**Comment by BrandonDusseau** [comment]
I also had this problem after upgrading and it persisted after uninstalling/reinstalling. The old settings in ~/.atom/config.cson does not appear to get purged or transitioned to the new settings, so they appear alongside "default" settings that come with the package. Note that in the screenshot I have already moved the settings out of their old positions.

![screen shot 2015-07-14 at 4 09 43 pm](https://cloud.githubusercontent.com/assets/3901864/8683799/c9e7265c-2a42-11e5-87c9-45c90325f700.png)

**Comment by steelbrain** [comment]
That's a known issue with atom, not `linter-phpcs`'s fault. :)

**Comment by steelbrain** [comment]
Also, You might wanna see https://github.com/AtomLinter/Linter/issues/726

**Comment by lark1n** [comment]
Hi! I have the same issue on Mac OS Yosemite

<img width="480" alt="2015-08-26 11 44 55" src="https://cloud.githubusercontent.com/assets/2790873/9489200/e4ad8974-4be7-11e5-8e10-3abd87f64f00.png">

My init file:

<img width="912" alt="2015-08-26 11 45 36" src="https://cloud.githubusercontent.com/assets/2790873/9489208/fca025b4-4be7-11e5-9b78-77493614e89a.png">

phpcs console output:

<img width="842" alt="2015-08-26 11 46 32" src="https://cloud.githubusercontent.com/assets/2790873/9489221/23069472-4be8-11e5-8ff5-f934b3211d4c.png">

linter-phpcs package settings:

<img width="912" alt="2015-08-26 11 47 11" src="https://cloud.githubusercontent.com/assets/2790873/9489239/43e10736-4be8-11e5-8408-34a03a9bb087.png">

I tried to restart the atom and the whole system, helps nothing

**Comment by Arcanemagus** [comment]
Can you file this as a new issue? What you are seeing is something entirely different than what this issue is about and there is no sense spamming the others in this issue attempting to diagnose it.

**Comment by lark1n** [comment]
I have created a new issue - https://github.com/AtomLinter/linter-phpcs/issues/54
