### ISSUE TITLE
parse php files based on presence of <?php ?> tags rather than file suffix?

### ISSUE THREAD

**Issue by iquitelikeegg** [AtomLinter/linter-phpcs#4]
Presently working on a Drupal project and Drupal uses some special scripts (eg. modules) which do not use standard .php suffix.

Would it be difficult to enable codesniffing based on the presence of <?php tags rather that just suffixes?

Thanks,
Vince

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-phpcs/pull/30
