### ISSUE TITLE
Use php -l with phpcs ?

### ISSUE THREAD

**Issue by ChristopheBoucaut** [AtomLinter/linter-phpcs#40]
I wrote a bad php syntax (eee="ee") and the plugin doesn't throw an error. It's normal ? php -l doesn't run with phpcs ?

**Comment by steelbrain** [comment]
I am not sure if I understand what you're saying, Please do explain.

**Comment by ChristopheBoucaut** [comment]
In sublime text, when i save my file, the plugin executes phpcs to check rules defined in the standard and it executes `php -l file.php` to check the syntax is valid. After, it merges two returns and it displays them. For example, if i forget a ";" at the end of my line, the plugin throws an error to indicate me.

**Comment by steelbrain** [comment]
I think You might wanna use linter-php for that. 'cause these linter providers are focused one per tool.

**Comment by ChristopheBoucaut** [comment]
Okay. Thank for your answer =).
