### ISSUE TITLE
Error: spawn phpcs ENOENT

### ISSUE THREAD

**Issue by ian-rose** [AtomLinter/linter-phpcs#41]
This may be related to https://github.com/AtomLinter/linter-phpcs/issues/6, as people were seeing similar issues there.

After I updated to the latest version of `linter-phpcs` I now seeing the following error when I save files:

```
Error: spawn phpcs ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
    at child_process.js:1127:20
    at process._tickCallback (node.js:357:13)
```

Additionally, the linter is no longer linting... I have files with known issues that show as "No Issues" in Atom.

The settings I have configured in `~/.atom/config.cson` are:
```
  "linter-phpcs":
    phpcsExecutablePath: "/usr/local/bin/phpcs"
    standard: "Drupal"
```

The "Drupal" coding standard is recognized by `phpcs`:
```bash
user@localhost$ phpcs -i
The installed coding standards are Drupal, MySource, PEAR, PHPCS, PSR1, PSR2, Squiz and Zend
```

The `phpcs` path is set correctly:
```bash
user@localhost$ which phpcs
/usr/local/bin/phpcs
```

My system is set up with the following software:

Software|Version
--------|-------
Mac OS X|10.10.3
phpcs|2.3.3 (stable)
Atom|1.0.2
linter|1.2.3
linter-phpcs|1.0.5

**Comment by steelbrain** [comment]
`phpcsExecutablePath` should be renamed to `executablePath`

**Comment by ian-rose** [comment]
Changing `phpcsExecutablePath` to `executablePath` fixed the issue.

**Comment by jasperkennis** [comment]
Setting the path in the settings interface in Atom should also store the value under the right key, shouldn't it?
