### ISSUE TITLE
Is it a mistake?

### ISSUE THREAD

**Issue by okonomiyaki3000** [AtomLinter/linter-phpcs#44]
Why does the plugin settings screen have two fields for 'Standard' and two fields for 'Executable Path'?

**Comment by steelbrain** [comment]
Well, It's not really a mistake in this package but an atom bug, Are you able to reproduce this with
```
mv ~/.atom ~/.atom-bkp
apm install linter
apm install linter-phpcs
```

**Comment by hylle** [comment]
I noticed the extra fields went away after opening my "config.cson" and clearing out the references to the deprecated settings.
