### ISSUE TITLE
Cannot read property 'messages' of undefined

### ISSUE THREAD

**Issue by davidbarratt** [AtomLinter/linter-phpcs#46]
Whenever I save a PHP file, I get this error:

```
Cannot read property 'messages' of undefined
TypeError: Cannot read property 'messages' of undefined
  at /Users/dbarratt/.atom/packages/linter-phpcs/lib/main.coffee:75:40
  at process._tickCallback (node.js:367:9)
```

**Comment by davidbarratt** [comment]
Seems like it was the version of PHPCS I was running.

**Comment by davidbarratt** [comment]
Hmm, maybe not.. but it does appear to happen on some files and not others.. :(

**Comment by steelbrain** [comment]
A minimal repro case please?

**Comment by shaunburdick** [comment]
I was able to reproduce it for files I have ignored in my xml config file.
If you have an exclude pattern setup: `<exclude-pattern>*/somePath/*</exclude-pattern>`
PHPCS will not output anything for that file. The code assumes there will always be an output.

**Comment by steelbrain** [comment]
@shaunburdick Right! Thanks!
/cc @Arcanemagus

**Comment by shaunburdick** [comment]
A quick check for `result.files[filePath].messages` before you run the map on line 79 should do it for you.

**Comment by Arcanemagus** [comment]
@steelbrain you are the one that re-wrote this linter :wink:.

If you wanted me to look into this I can in ~5 hours...
