### ISSUE TITLE
error message display obscures code window and atom UI elements

### ISSUE THREAD

**Issue by iquitelikeegg** [AtomLinter/linter-phpcs#47]
When you open a file with large numbers of code sniffer errors (try opening "functions.php" in wordpress for this!) the error message window opens up and totally obscures the code window and even the Atom UI elements, like the code window tabs.

**Comment by steelbrain** [comment]
Screenshot please?

**Comment by iquitelikeegg** [comment]
![screen shot 2015-07-21 at 15 50 36](https://cloud.githubusercontent.com/assets/2210234/8803724/61dd4158-2fc0-11e5-89fe-bafe798668f0.png)

Here!

**Comment by steelbrain** [comment]
That's actually a theme issue, Please switch to the default theme to fix this :smiley:

**Comment by iquitelikeegg** [comment]
really? I don't think I've ever fiddled with the themes, I'm using the "one-dark" theme for reference. I also tried Atom Dark and Atom Light and the issue seems to exist.

**Comment by iquitelikeegg** [comment]
oops, I keep posting because I'm trying to line break! Anyway - which theme are you using where this isn't happening?

**Comment by steelbrain** [comment]
See https://github.com/atom-community/linter/issues/746

**Comment by iquitelikeegg** [comment]
Hmm, curious - reloading the program seems to have resolved it. To confirm I didn't change any settings.

I do have some custom styles.less stuff - but nothing that interacts with the linter-panel. 

Anyway it's sorted - many thanks for your speedy help!
