### ISSUE TITLE
return error when subscript start with \\

### ISSUE THREAD

**Issue by RustJason** [AtomLinter/linter-phpcs#48]
on [line79](https://github.com/AtomLinter/linter-phpcs/blob/master/lib/main.coffee#L79), if filepath start with two backslash "\\\\"(because I am editing a network file),
then even if phpcs return errors, It will just return from this line.

**Comment by steelbrain** [comment]
I am not sure if I follow, can you please post the value of `filePath`? Make sure to remove any sensitive info related to it, if any.

**Comment by Red-wolf-s-husband** [comment]
filePath = \\10.0.0.0\something\Yarbootstrap.php
by the way, How would you express this since you don't understand it at first?

**Comment by steelbrain** [comment]
I am not really a linter-phpcs user myself, I just found the repo to be abandoned and there were a lot of open issues so I thought to take it over.
and I see that the filePath is a bit different than traditional, but we aren't really doing any magical thing by ourselves, we get filePath from atom, pass it to phpcs, and filter it's messages for that filePath.
The errors should work just fine if the filePaths reported by both are the same. If they are not, however then I would need some examples about how that network mount's path is changed by phpcs so I can make the code act accordingly.

**Comment by Red-wolf-s-husband** [comment]
No, I think "unless" has problem. I can see all the data return by phpcs.
But it should go down to line80. Let me show you a picture.

This function will return from this line.
![ksy8xdm1o ns oguzva0r v](https://cloud.githubusercontent.com/assets/4018764/8848237/5d0e1108-3168-11e5-8f30-16fee441e13b.png)
![_y bxai3 8l172 71 vg1u](https://cloud.githubusercontent.com/assets/4018764/8848243/66f8299c-3168-11e5-981c-2a16924ce6ad.png)


I think this would make a lot of sence.

**Comment by steelbrain** [comment]
Well, we could do `Object.keys(result.files)[0]` to get the first one, regardless of the path.

**Comment by Red-wolf-s-husband** [comment]
Notice that in the middle of the filePath, CN was being write as uppercase in the first pic, but lowercase in the second one.

**Comment by steelbrain** [comment]
Yep, `phpcs` when giving output, makes the paths lowercase I guess. In any case, the solution I mentioned above would work in every scenario.

**Comment by Red-wolf-s-husband** [comment]
Let me check first.

**Comment by Arcanemagus** [comment]
With other linters that "manipulate" the file path in their output I have simply ignored what they report it as and forced it to be the original file path Atom uses. Otherwise the errors show up in Project scope, but no file will ever be associated with them.

**Comment by Arcanemagus** [comment]
@RustJason is this still an issue?

**Comment by RustJason** [comment]
@Arcanemagus Sorry, don't use Atom now
