### ISSUE TITLE
Compatible with lintOnFly?

### ISSUE THREAD

**Issue by aendrew** [AtomLinter/linter-phpcs#52]
Hi!
I'm able to get atom-linter's `lintOnFly` to work with other linters (linter-jshint, for instance), but it doesn't seem to work with linter-phpcs. Is this intentional, a bug, or a localised issue with my install?

Thanks!

**Comment by Arcanemagus** [comment]
`linter-phpcs` currently doesn't support this as `phpcs` doesn't support linting a file from stdin so we must use the raw file. It would actually be somewhat simple to implement this using the new tempFile function from the `atom-linter` helper module, but it currently doesn't work this way.

**Comment by skyrpex** [comment]
@Arcanemagus it indeed does. I implemented it in the PR above.

**Comment by Arcanemagus** [comment]
Awsome :smile: 

Quite glad to be justifiably wrong.

**Comment by skyrpex** [comment]
:+1: I'm glad too! Haha.

**Comment by pixelchutes** [comment]
Awesome, thanks! :clap:

**Comment by aendrew** [comment]
Amazing! Many thanks!
