### ISSUE TITLE
Error parsing PHPCS response

### ISSUE THREAD

**Issue by lark1n** [AtomLinter/linter-phpcs#54]
Hi! I have this issue on Mac OS Yosemite (10.10.5) with build-in PHP

<img width="480" alt="2015-08-26 11 44 55" src="https://cloud.githubusercontent.com/assets/2790873/9499490/7a75249a-4c28-11e5-8366-3bd5509fd283.png">

My init file:

<img width="912" alt="2015-08-26 11 45 36" src="https://cloud.githubusercontent.com/assets/2790873/9499513/98964fda-4c28-11e5-97ed-38043b111e58.png">

phpcs console output:

<img width="842" alt="2015-08-26 11 46 32" src="https://cloud.githubusercontent.com/assets/2790873/9499527/a7276e8a-4c28-11e5-9d5a-c9a4599b1f79.png">

linter-phpcs package settings:

<img width="912" alt="2015-08-26 11 47 11" src="https://cloud.githubusercontent.com/assets/2790873/9499553/b4aa8fe2-4c28-11e5-9f7c-82757f1ea38d.png">

**Comment by Arcanemagus** [comment]
Can you post the relevant contents of your `config.cson` file? I recently saw another person on OS X that had pasted in the path to their executable from the command line and had accidentally included a `\n` in there (which wouldn't be easily visible in the UI).

**Comment by lark1n** [comment]
```cson
"*":
  "exception-reporting":
    userId: "0cd4acb1-9d95-a388-9fca-11c9c65434fc"
  welcome:
    showOnStartup: false
  core:
    disabledPackages: [
      "symbol-gen"
      "welcome"
      "styleguide"
      "open-on-github"
      "metrics"
      "markdown-preview"
      "language-yaml"
      "language-toml"
      "language-ruby-on-rails"
      "language-ruby"
      "language-python"
      "language-perl"
      "language-objective-c"
      "language-mustache"
      "language-make"
      "language-java"
      "language-go"
      "language-gfm"
      "language-csharp"
      "language-coffee-script"
      "language-clojure"
      "language-c"
      "autosave"
      "archive-view"
    ]
  editor:
    invisibles: {}
    showIndentGuide: true
    scrollPastEnd: true
  linter: {}
  minimap: {}
  "linter-php": {}
  "linter-phpmd":
    executablePath: "/usr/local/bin/phpmd"
  "linter-phpcs":
    executablePath: "/usr/local/bin/phpcs"
  "git-plus": {}

```

**Comment by lark1n** [comment]
<img width="912" alt="2015-08-26 20 00 39" src="https://cloud.githubusercontent.com/assets/2790873/9500276/26659056-4c2d-11e5-9a99-4e1c3a61ed60.png">

**Comment by Arcanemagus** [comment]
Can you open Developer Tools in Atom and put a breakpoint at lines 105 and 106 of the main.coffee for `linter-phpcs`?

At line 105 in the console run `JSON.stringify({command, parameters})` and paste the output here. Continue execution and at line 106 grab the output of `JSON.stringify(result)` and paste it here.

**Comment by lark1n** [comment]
105 line:
```json
"{"command":"/usr/local/bin/phpcs","parameters":["--ignore=*.blade.php,*.twig.php","--warning-severity=1","--standard=PSR2","--report=json","/Library/WebServer/Documents/next/application/controllers/user.php"]}"
```

and 106 line:
```json
""\nFatal error: Uncaught exception 'UnexpectedValueException' with message 'DirectoryIterator::__construct(/usr/local/etc/php-code-sniffer/Standards): failed to open dir: No such file or directory' in /usr/local/Cellar/php-code-sniffer/2.3.2/CodeSniffer.php on line 2153\n\nUnexpectedValueException: DirectoryIterator::__construct(/usr/local/etc/php-code-sniffer/Standards): failed to open dir: No such file or directory in /usr/local/Cellar/php-code-sniffer/2.3.2/CodeSniffer.php on line 2153\n\nCall Stack:\n    0.0017     225400   1. {main}() /usr/local/Cellar/php-code-sniffer/2.3.2/scripts/phpcs:0\n    0.0180    1541416   2. PHP_CodeSniffer_CLI->runphpcs() /usr/local/Cellar/php-code-sniffer/2.3.2/scripts/phpcs:25\n    0.0192    1599800   3. PHP_CodeSniffer_CLI->process() /usr/local/Cellar/php-code-sniffer/2.3.2/CodeSniffer/CLI.php:95\n    0.0205    1608832   4. PHP_CodeSniffer_CLI->validateStandard() /usr/local/Cellar/php-code-sniffer/2.3.2/CodeSniffer/CLI.php:809\n    0.0206    1609384   5. PHP_CodeSniffer::getInstalledStandards() /usr/local/Cellar/php-code-sniffer/2.3.2/CodeSniffer/CLI.php:1032\n    0.0209    1614808   6. DirectoryIterator->__construct() /usr/local/Cellar/php-code-sniffer/2.3.2/CodeSniffer.php:2153\n\n""
```

**Comment by Arcanemagus** [comment]
Ah, so the issue is that `phpcs` is crashing :stuck_out_tongue:.

```
Fatal error: Uncaught exception 'UnexpectedValueException' with message 'DirectoryIterator::__construct(/usr/local/etc/php-code-sniffer/Standards): failed to open dir: No such file or directory' in /usr/local/Cellar/php-code-sniffer/2.3.2/CodeSniffer.php on line 2153

UnexpectedValueException: DirectoryIterator::__construct(/usr/local/etc/php-code-sniffer/Standards): failed to open dir: No such file or directory in /usr/local/Cellar/php-code-sniffer/2.3.2/CodeSniffer.php on line 2153

Call Stack:
    0.0017     225400   1. {main}() /usr/local/Cellar/php-code-sniffer/2.3.2/scripts/phpcs:0
    0.0180    1541416   2. PHP_CodeSniffer_CLI->runphpcs() /usr/local/Cellar/php-code-sniffer/2.3.2/scripts/phpcs:25
    0.0192    1599800   3. PHP_CodeSniffer_CLI->process() /usr/local/Cellar/php-code-sniffer/2.3.2/CodeSniffer/CLI.php:95
    0.0205    1608832   4. PHP_CodeSniffer_CLI->validateStandard() /usr/local/Cellar/php-code-sniffer/2.3.2/CodeSniffer/CLI.php:809
    0.0206    1609384   5. PHP_CodeSniffer::getInstalledStandards() /usr/local/Cellar/php-code-sniffer/2.3.2/CodeSniffer/CLI.php:1032
    0.0209    1614808   6. DirectoryIterator->__construct() /usr/local/Cellar/php-code-sniffer/2.3.2/CodeSniffer.php:2153
```

It looks like it's trying to access a code standard file that doesn't exist?
(`/usr/local/etc/php-code-sniffer/Standards`)

**Comment by Arcanemagus** [comment]
Does it work on the file you were editing from the command line?

**Comment by lark1n** [comment]
Ok, I understand now :)
This falls, if we use the parameter
```
--standard=PSR2
```
And without this parameter it works fine!

**Comment by Arcanemagus** [comment]
So it looks like for some reason your PSR2 standard definition is broken on your installation. You can specify a different standard in your settings, or create a custom `phpcs.xml` file with your own ruleset.

Personally I would look into why that is broken though.

Since this isn't an issue with `linter-phpcs` would you mind closing this issue? Feel free to ask anything though and I'll see if I can help.

**Comment by lark1n** [comment]
Yes, this issue closed. This is not a plugin problem. I think that is because I have installed phpcs through composer (not PEAR)

**Comment by steelbrain** [comment]
@Arcanemagus how about you log to `console.error(data)` if parsing fails? It'll help debugging

**Comment by Arcanemagus** [comment]
@steelbrain That should probably be done in the core `linter`. The "known bug on OS X" error message is shown whenever _anything_ goes wrong with running the linter, and is almost always the wrong message now.

**Comment by steelbrain** [comment]
@Arcanemagus that is `linter-jshint`.

**Comment by Arcanemagus** [comment]
What is? The "known bug in OS X"? See the first screenshot posted here...

**Comment by robneu** [comment]
I'm getting this almost constantly now after the last update...

**Comment by skyrpex** [comment]
@robneu, looks like #60?

**Comment by robneu** [comment]
@skyrpex It does seem related. I've been seeing that issue as well.

**Comment by Arcanemagus** [comment]
The error message here is rather misleading, and is only shown in out dated versions of the helper library. This probably needs to just be updated.

The root cause of that message being shown is for some reason it couldn't launch phpcs (permissions? couldn't find the file name? etc...). If you are on Windows there is a bug in node where you need to explicitly add the .bat to the executable for it to work.

**Comment by patrickmaciel** [comment]
I ge this error after **upgrade to El Capitan** and I solve this running just `brew reinstall php-code-sniffer`

**Comment by corysimmons** [comment]
Can confirm this bug. I deleted a standard and now `phpcs -i` is broken. Reinstalling doesn't help.

**Comment by mrpritchett** [comment]
Still getting this error here.

**Comment by Arcanemagus** [comment]
@mrpritchett Can you please file a new issue as there are many different things that could be causing this. In your new issue please include the information being logged to the console, thanks!

Locking this so everyone in this thread doesn't keep getting spammed for unrelated issues.
