### ISSUE TITLE
Error when saving

### ISSUE THREAD

**Issue by Mech7** [AtomLinter/linter-phpcs#55]
I get the following error when saving, phpcs is installed on my system only with composer (global) not PEAR
```
Error: spawn phpcs ENOENT
  at exports._errnoException (util.js:734:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)
```

```
$ phpcs --version
PHP_CodeSniffer version 2.3.3 (stable) by Squiz (http://www.squiz.net)
```

**Comment by steelbrain** [comment]
Are you on OSX?

**Comment by steelbrain** [comment]
Blame the apple guys for this, OSX doesn't pass the env variables to gui apps correctly. You can always start atom from CLI to get them correctly, or you can manually specify the exe path in the linter configuration

**Comment by waxim** [comment]
I get the same error when I don't close out the php tag, when I do the error goes, not sure why it would be the case though?

**Comment by Arcanemagus** [comment]
I'm going to close this issue, there have been several changes put in place in helper modules to try to work around this, and there is a proper "workaround" of this design choice of Apple's available at the user level.
