### ISSUE TITLE
spawn ENOENT

### ISSUE THREAD

**Issue by Cipa** [AtomLinter/linter-phpcs#6]
Just installed and the console opens every time I open a php file.

Here is what I see when I start atom by clicking index.php in a project.
Atom 0.122.0/ MaxOs 10.9.4 

![screen shot 2014-08-15 at 9 47 11 am](https://cloud.githubusercontent.com/assets/293377/3933710/f6d122d8-2482-11e4-9fe5-7dd6f1cd7e26.png)

Any ideas?

Thanks

**Comment by steelbrain** [comment]
Fixed by Fixed by https://github.com/AtomLinter/linter-phpcs/pull/30

**Comment by Arcanemagus** [comment]
Are you sure this was fixed in #30?

I am now getting the following on v1.0.1:
```
spawn phpcs ENOENT
Error: spawn phpcs ENOENT
  at exports._errnoException (util.js:734:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)
```

However no further information is being shown in the console.

**Comment by steelbrain** [comment]
@Arcanemagus it means that phpcs binary wasn't found in your `$PATH`. You can fix it by giving it the exact location to PHPCS in settings

**Comment by Arcanemagus** [comment]
It looks like even though `phpcs` is in the $PATH, it needs to be explicitly told where it is on Windows.
```
PS C:\Users\Arcanemagus> where.exe phpcs
C:\php5\phpcs
C:\php5\phpcs.bat
PS C:\Users\Arcanemagus> phpcs --version
PHP_CodeSniffer version 2.3.2 (stable) by Squiz (http://www.squiz.net)
PS C:\Users\Arcanemagus> C:\php5\phpcs.bat --version
PHP_CodeSniffer version 2.3.2 (stable) by Squiz (http://www.squiz.net)
```

Setting the executable path to the full `C:\php5\phpcs.bat` causes it to work. I'm guessing it is simply trying `phpcs` and is not getting automatically expanded to `phpcs.bat` for some reason.

**Comment by steelbrain** [comment]
I think that's a nodejs bug for windows. https://github.com/joyent/node/issues/2318

**Comment by Arcanemagus** [comment]
Subscribed, thanks :wink:.

**Comment by ian-rose** [comment]
I am now seeing this error after I updated to the latest version of `linter-phpcs` this morning (before updating everything worked correctly, and I didn't change any settings during or after the update):

```
Error: spawn phpcs ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
    at child_process.js:1127:20
    at process._tickCallback (node.js:357:13)
```

The settings I have configured in `~/.atom/config.cson` are:
```
  "linter-phpcs":
    phpcsExecutablePath: "/usr/local/bin/phpcs"
    standard: "Drupal"
```

The "Drupal" coding standard is recognized by `phpcs`:
```bash
user@localhost$ phpcs -i
The installed coding standards are Drupal, MySource, PEAR, PHPCS, PSR1, PSR2, Squiz and Zend
```

The `phpcs` path is set correctly:
```bash
user@localhost$ which phpcs
/usr/local/bin/phpcs
```

My system is set up with the following software:

Software|Version
--------|-------
Mac OS X|10.10.3
phpcs|2.3.3 (stable)
Atom|1.0.2
linter|1.2.3
linter-phpcs|1.0.5

**Comment by samirfor** [comment]
Thanks @steelbrain. I just did:
```shell
sudo apt-get install php-codesniffer
```
