### ISSUE TITLE
When Code Standard is set to PSR2, PHPCS is throwing comment / documentation errors.

### ISSUE THREAD

**Issue by AustP** [AtomLinter/linter-phpcs#73]
I just updated linter-phpcs to the latest version (1.2.1) and now PHPCS is throwing comment / documentation errors. I have the Code Standard defaulted to [PSR2](http://www.php-fig.org/psr/psr-2/). There it states that:

> There are many elements of style and practice intentionally omitted by this guide. These include but are not limited to:
> - Declaration of global variables and global constants
> - Declaration of functions
> - Operators and assignment
> - Inter-line alignment
> - **Comments and documentation blocks**
> - Class name prefixes and suffixes
> - Best practices

Any way that we can get this fixed?

**Comment by Arcanemagus** [comment]
`linter-phpcs` only exposes the results of running `phpcs` on your code, you probably want to file this issue on [`phpcs`](https://github.com/squizlabs/PHP_CodeSniffer).

Marking this as closed since it isn't an issue with `linter-phpcs`.

**Comment by AustP** [comment]
@Arcanemagus - I'm a bit confused because I've never updated phpcs, only linter-phpcs. That's what lead me to believe that it was this package that caused the issue... Any thoughts?

**Comment by Arcanemagus** [comment]
The only thing that I can think that an update of `linter-phpcs` would change would be if you were on a _very_ old version that didn't support automatically searching out a `phpcs.xml` file and it is now searching and finding one that specifies that.

When you run `phpcs` manually on the file from the same directory that the file is in do you see the messages in that output?

**Comment by Arcanemagus** [comment]
Also what messages specifically are you seeing?

**Comment by Arcanemagus** [comment]
@AustP @pfefferle made a good catch where it currently would ignore any custom defined standard if it couldn't find a config file. I thought that `phpcs` defaulted to PSR2, but it might be including more than that by default. Can you try v1.2.2 and see if you are still seeing this?

**Comment by AustP** [comment]
@Arcanemagus @pfefferle - Just updated to 1.2.2 and it fixed the issue. Thanks for your hard work. :heart:

**Comment by pfefferle** [comment]
your welcome! i had the same issue this morning, so I tried to figure out why ;)

**Comment by Arcanemagus** [comment]
I really need to set up actual testing on this repo so things like that get caught...
