### ISSUE TITLE
TypeError: Cannot read property 'stdin' of undefined

### ISSUE THREAD

**Issue by jptaranto** [AtomLinter/linter-phpcs#75]
Just started getting this although I can't pin point what has been changed. I did have everything working pretty well previously.

`TypeError: Cannot read property 'stdin' of undefined`

Stack trace:

```
TypeError: Cannot read property 'stdin' of undefined
  at /Users/jack/.atom/packages/linter-phpcs/node_modules/atom-linter/lib/helpers.coffee:55:31
  at Object.module.exports.Helpers._exec (/Users/jack/.atom/packages/linter-phpcs/node_modules/atom-linter/lib/helpers.coffee:25:16)
  at Object.module.exports.Helpers.exec (/Users/jack/.atom/packages/linter-phpcs/node_modules/atom-linter/lib/helpers.coffee:16:13)
  at Object.provider.lint (/Users/jack/.atom/packages/linter-phpcs/lib/main.coffee:103:24)
  at Promise.then._this.emitter.emit.linter (/Users/jack/.atom/packages/linter/lib/linter-registry.coffee:59:22)
  at LinterRegistry.triggerLinter (/Users/jack/.atom/packages/linter/lib/linter-registry.coffee:58:16)
  at /Users/jack/.atom/packages/linter/lib/linter-registry.coffee:52:17
  at Array.map (native)
  at /Users/jack/.atom/packages/linter/lib/linter-registry.coffee:50:27
```

Atom version 1.0.19

linter version 1.8.1

linter-phpcs version 1.2.2

phpcs is installed via composer

**Comment by Arcanemagus** [comment]
Is this happening for all files? If not, can you provide a file that triggers this?
What OS are you on?

From the stack trace it looks like the helper module successfully spawns the process, but then isn't able to talk to it for some reason...

**Comment by jptaranto** [comment]
It's happening on all php files yeah. I'm on El Capitan (OS X 10.11.0).

**Comment by jptaranto** [comment]
Haha, now that I think of it, it's probably the El Capitan update that broke it!

**Comment by Arcanemagus** [comment]
I wonder if they broke communication with subprocesses in the name of "security"? That seems like something Apple would think is a good idea...

Anyway, can you try manually testing `stdin` input by doing the following in a terminal:
```
cat /path/to/a/file.php | phpcs
```

**Comment by opensussex** [comment]
any resolution to this issue ? having the same problem .

**Comment by Arcanemagus** [comment]
I have no way to test this, so without feedback (like the result of running the test in my last message...) I can't even begin to try to debug this.

**Comment by opensussex** [comment]
@Arcanemagus - actually, I was able to solve the problem (I am running it on OS X) - for me the path to phpcs was incorrect in the config, when I changed this the error went and all working fine.

**Comment by Arcanemagus** [comment]
Interesting, it should have been a different error if the path was wrong, I'm glad you got it figured out though.

@jptaranto since you haven't responded in over a week I'm going to mark this as closed, feel free to re-open the issue if you are still having problems though.

**Comment by opensussex** [comment]
@Arcanemagus I think it was an issue with a version of phpcs I had installed, so I changed the path to a different installed version - and it worked ok - would that be more consistent with the error? (rather than it just being a wrong path and not finding phpcs ...)

**Comment by Arcanemagus** [comment]
That makes slightly more sense, although this entire issue makes very little sense as the only way I can think to trigger it is for the process to be spawned, but then Atom being unable to communicate with it.

**Comment by jptaranto** [comment]
@Arcanemagus very sorry I didn't respond. Life got in the way a little bit. I've just run `stdin` and it seems to be working fine. I got the below output:

```FILE: STDIN
--------------------------------------------------------------------------------
FOUND 8 ERROR(S) AND 2 WARNING(S) AFFECTING 4 LINE(S)
--------------------------------------------------------------------------------
  4 | ERROR   | There must be exactly one blank line before the tags in file
    |         | comment
  6 | WARNING | PHP version not specified
  6 | ERROR   | Missing @category tag in file comment
  6 | ERROR   | Missing @package tag in file comment
  6 | ERROR   | Missing @author tag in file comment
  6 | ERROR   | Missing @license tag in file comment
  6 | ERROR   | Missing @link tag in file comment
 20 | ERROR   | Line indented incorrectly; expected at least 4 spaces, found 2
 20 | WARNING | Line exceeds 85 characters; contains 180 characters
 21 | ERROR   | Line indented incorrectly; expected at least 4 spaces, found 2
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------
```

**Comment by Arcanemagus** [comment]
From the last line it looks like you are using an ancient version of `phpcs` @jptaranto, can you try upgrading that to the latest?

**Comment by jptaranto** [comment]
phpcs is now version 2.3.4 and it's working!

Unrelated but drupal coder needs to be updated to 8.x when our ci is using 7.x... I'll see how that goes.

Thanks mate and sorry it turned out to be something so trivial :)
