### ISSUE TITLE
Process doesn't stop.

### ISSUE THREAD

**Issue by ChristopheBoucaut** [AtomLinter/linter-phpcs#78]
Sometimes, the process launched doesn't stop and it results a crash for Atom. If I save many times in a short time, multiples processes are launched and they block my computer for few seconds. Every time, I must kill processes by myself.

Result with htop :
![phpcs](https://cloud.githubusercontent.com/assets/2339969/11037776/e78c21de-86ff-11e5-94b6-f90929de6a0a.png)

I have :
* Kubuntu 15.10
* PHP_CodeSniffer version 2.3.4 (stable) by Squiz (http://www.squiz.net)
* Atom 1.0.19
* linter 1.10.0
* linter-phpcs 1.3.0

I don't have the same problem with other linter-* plugin so I think the problem is in linter-phpcs.

Or maybe, the problem come of standard which is in a infinite loop or something like that if the problem doesn't come from the plugin.

**Comment by Arcanemagus** [comment]
Just wanted to say that I haven't been ignoring this, and have seen it myself. I just haven't had time to come up with a proper solution and implement it yet.

**Comment by ChristopheBoucaut** [comment]
Okey. No problem, take your time. You developed this plugin on your time and I thank you for it =). If I have the time, I will try to watch the code to help you now you confirmed to have the same problem :).

**Comment by evilebottnawi** [comment]
@ChristopheBoucaut what standard you use?

**Comment by ChristopheBoucaut** [comment]
@evilebottnawi , i use this standard (for Sf2) : https://github.com/escapestudios/Symfony2-coding-standard

**Comment by Arcanemagus** [comment]
Just an FYI: This will most likely be handled here: https://github.com/AtomLinter/atom-linter/issues/81

**Comment by ChristopheBoucaut** [comment]
Oh ! Nice :) Thank you for the info.

**Comment by skyrpex** [comment]
I've been experiencing this, too. Limiting the execution time would be just a workaround for the real problem (phpcs hanging on, consuming CPU).

Anyone knows why phpcs hangs like that?

**Comment by ricpelo** [comment]
I have the same problem, too. I need to disable the plugin, unfortunately :(.

**Comment by ChristopheBoucaut** [comment]
In the linter plugin, a timeout to process execution is implemented. Just wait it is released and that linter-phpcs is updated.

**Comment by Arcanemagus** [comment]
Huh, thought we had released that already, thanks for making me check @ChristopheBoucaut!

Will be publishing a version with that soon and updating the min version this requires.

**Comment by Arcanemagus** [comment]
A 10 second timeout has been added in v1.3.1 (assuming Atom updates the dependencies properly... it sometimes has issues). Let me know if you continue seeing this after updating!

**Comment by ChristopheBoucaut** [comment]
thank you. I will update tomorrow and I will test on this week.

**Comment by ChristopheBoucaut** [comment]
I have tested in this week and this fix is ok :) Thank!
