### ISSUE TITLE
Please allow specifying other parameters

### ISSUE THREAD

**Issue by N4M3Z** [AtomLinter/linter-phpcs#98]
Please consider supporting other phpcs parameters, namely `-s` so it is possible to easily determine which rule is affecting the current setup.

**Comment by Arcanemagus** [comment]
A PR supporting this would be welcome, otherwise I'll try to get to this at some point.

**Comment by Arcanemagus** [comment]
(Although looking at the option, it looks like something that should be enabled _always_, so I'm not sure this should be an option.)

**Comment by N4M3Z** [comment]
I agree with that point.

**Comment by UziTech** [comment]
I created a pull request with an option to disable it.

I figured an option to turn it off would be nice since it takes a bit of space away from the actual message and some people don't need/want to see it. 

https://github.com/AtomLinter/linter-phpcs/pull/136
